soutaro/steep

- lib/steep/interface.rb
- lib/steep/signature/interface.rb
- lib/steep/type_assignability.rb
- smoke/array/b.rb
- stdlib/builtin.rbi
- test/interface_test.rb
- test/type_assignability_test.rb
> Fix parametrized types compatibility test

- lib/steep/drivers/check.rb
- lib/steep/module_name.rb
- lib/steep/type_construction.rb
- test/module_name_test.rb
- test/type_construction_test.rb
Add support for nested module definition. 🗜 
* Nested module/class definition can be auto implemented
* Module/class definition with concatenated name can be auto implemented
> Nested module

- lib/steep.rb
- lib/steep/cli.rb
- lib/steep/drivers/scaffold.rb
`$ steep scaffold foo.rb` to generate a signature for the classes defined in the file. The generated signatures would be a good starting point for writing types.
The generated signature will look like the following:
```
class Steep::Drivers::Scaffold
@source_paths: any
@stdout: any
@stderr: any
@labeling: any
def initialize: (source_paths: any, stdout: any, stderr: any) -> any
def run: () -> any
end
Steep::Version: any
```
* All types are stubbed with `any`
* Class/module definitions are included
* Method definitions are included
* Constant assignments are included
* Instance variables are included
> Add scaffold command

- lib/steep/drivers/scaffold.rb
scaffold guesses a type of constants, instance variables, and return
values of a method by investigating the syntax tree of left-hand
expression or method body.
```
class Foo
CONST = 1              #=> Foo:CONST: Integer
def func
@ivar = "Str"        #=> @ivar: String
cond? ? :foo : :bar  #=> def func: () -> Symbol
end
end
```
> Add a simple type guesser into scaffold

- lib/steep/ast/types/any.rb
- lib/steep/ast/types/bot.rb
- lib/steep/ast/types/class.rb
- lib/steep/ast/types/instance.rb
- lib/steep/ast/types/intersection.rb
- lib/steep/ast/types/name.rb
- lib/steep/ast/types/self.rb
- lib/steep/ast/types/top.rb
- lib/steep/ast/types/union.rb
- lib/steep/ast/types/var.rb
- lib/steep/ast/types/void.rb
- lib/steep/parser.y
- stdlib/builtin.rbi
- test/type_parsing_test.rb
* Fix type parsing
* Allow nullable type to be like `Integer?`
> Fix type parsing

- lib/steep/ast/types/nil.rb
- lib/steep/subtyping/check.rb
- test/type_construction_test.rb
> Fix literal type resolve

- LICENSE
> Steep is licensed under the MIT license

- lib/steep/drivers/langserver.rb
- lib/steep/project.rb
- lib/steep/source.rb
- sig/project.rbi
- test/langserver_test.rb
- test/source_test.rb
It prints the type of the node on hover now!
Todo:
- Should print type of the local variable?
- Should print type of method?
> Implement hover

- lib/steep/drivers/langserver.rb
- test/langserver_test.rb
Instead of waiting for `.rb` file edit,  publish diagnostics when editing `.rbi` file changes the diagnostics of open files.
> Let langserver publish diagnostics on all open files

- steep.gemspec
> Relax activesupport versioning dependency

- test/langserver_test.rb
It is the same patch as #98, but I mistakenly closed the pull request and cannot re-open it. So I created the new pull request with no-conflict.
> Do not make Steepfile in the project directory on test

- lib/steep/drivers/langserver.rb
- lib/steep/project/file.rb
- test/langserver_test.rb
- test/target_test.rb
Report annotation parsing error to LSP.
> Annotation parsing error

- lib/steep.rb
- lib/steep/type_construction.rb
- lib/steep/type_inference/logic.rb
- test/logic_test.rb
- test/type_construction_test.rb
This allows type checking the following Ruby code. 💪 
```rb
def foo(x)
return unless x    # Early return if x is nil.
puts(x + 1)        # x is Integer here.
end
```
> Revise flow sensitive typing on conditionals

- lib/steep/server/interaction_worker.rb
- test/interaction_worker_test.rb
Hover message formatting was broken... 😢
> Fix hover interaction error

- lib/steep/project/target.rb
- lib/steep/signature/errors.rb
- lib/steep/signature/validator.rb
- steep.gemspec
- test/target_test.rb
Handle errors raised during RBS environment loading.
> Improve RBS validation

- lib/steep/server/signature_worker.rb
- lib/steep/signature/validator.rb
- steep.gemspec
- test/type_construction_test.rb
- test/validation_test.rb
* Fix `SignatureOtherErrorStatus` handling
* Validate type aliases
* Validate type declaration namespaces
> Fix signature validation

- lib/steep/ast/types/factory.rb
- lib/steep/type_construction.rb
- test/type_construction_test.rb
> Fix literal typing with hint

- lib/steep/drivers/check.rb
- lib/steep/project/target.rb
- lib/steep/source.rb
- test/source_test.rb
The following code raises an error.
```ruby
case foo
when bar
something
else
end
```
> Support empty else clause in case

- lib/steep/type_construction.rb
> Let an empty array be `Array[untyped]`

- lib/steep/ast/types/factory.rb
- steep.gemspec
Method attributes are deprecated in RBS
> Update RBS to 0.11.0

- lib/steep/type_construction.rb
- smoke/module/a.rb
- test/type_construction_test.rb
Caused by #204, which changed the semantics of intersection types.
> Fix module typing

- lib/steep/server/master.rb
Restarting LSP servers with VSCode resulted in many unused Ruby processes. So, the problem is that the response to a `shutdown` request didn't send to the client properly because of `@shutdown` flag.
This patch stores the `id` of the `shutdown` request in `@shutdown_request_id`. It skips sending responses after the request, and once the response to `@shutdown_request_id` is sent, Steep exits.
> Process shutdown response before quit

- lib/steep/project/target.rb
- lib/steep/server/master.rb
- lib/steep/server/utils.rb
- test/lsp_utils_test.rb
It's much faster when the source code is long enough.
> Support incremental text document sync

- lib/steep/project/file.rb
- smoke/toplevel/Steepfile
- smoke/toplevel/a.rb
- smoke/toplevel/a.rbs
Fixes #225 reported by @JunichiIto.
> Setup module_context for toplevel def

- lib/steep/project/completion_provider.rb
That inserts a duplicated `@`.
> Fix instance variable completion

- smoke/regression/range.rb
- steep.gemspec
It is fixed in https://github.com/ruby/rbs/pull/418.
> Let Range[T] be covariant

- lib/steep/type_construction.rb
- test/master_test.rb
- test/type_construction_test.rb
> Type casgn

- lib/steep/subtyping/check.rb
- lib/steep/type_construction.rb
- steep.gemspec
- test/subtyping_test.rb
- test/type_construction_test.rb
`0.15.0` contains `bool` semantics update.
> Update rbs to 0.15.0

- lib/steep/project/target.rb
- test/target_test.rb
Let targets with `#vendor_path` load libraries too. It skips ignores `DEFAULT_STDLIB_ROOT`, but loads libraries from given repository.
> Fix repository loading

- lib/steep.rb
- lib/steep/index/rbs_index.rb
- lib/steep/index/signature_symbol_provider.rb
- lib/steep/index/source_index.rb
- lib/steep/server/master.rb
- lib/steep/server/signature_worker.rb
- lib/steep/type_construction.rb
- lib/steep/type_inference/constant_env.rb
- lib/steep/typing.rb
- test/index_test.rb
- test/rbs_index_test.rb
- test/signature_symbol_provider_test.rb
- test/signature_worker_test.rb
- test/source_index_test.rb
- test/type_construction_test.rb
> Support `workspace/symbol` feature

- lib/steep/ast/types/bot.rb
- lib/steep/ast/types/top.rb
> Fix string representation of Top and Bot

- lib/steep/type_construction.rb
- lib/steep/type_inference/logic_type_interpreter.rb
- test/type_construction_test.rb
Fixes the following problems:
* No method error skips type checking arguments
* Casting by assigning to `_` causes a crash on type-case
> Fix type case with cast

- bin/output_rebaseline.rb
Put empty `diagnostics` for files without output.
> Better rebaselineing

- lib/steep/drivers/check.rb
- lib/steep/drivers/diagnostic_printer.rb
- test/cli_test.rb
Source code for missing diagnostics may be out of date.
> Skip printing source code

- lib/steep/drivers/check.rb
- lib/steep/drivers/watch.rb
- lib/steep/server/master.rb
> Stop interaction worker when unnecessary

- lib/steep/annotation_parser.rb
- lib/steep/diagnostic/ruby.rb
- lib/steep/diagnostic/signature.rb
- lib/steep/services/type_check_service.rb
- test/type_check_service_test.rb
Fixes https://github.com/soutaro/steep/issues/337
> Syntax error

- lib/steep/subtyping/constraints.rb
- test/constraints_test.rb
- test/type_construction_test.rb
Fixes https://github.com/soutaro/steep/issues/340
> Fix constraint solving

- lib/steep/type_construction.rb
- test/type_construction_test.rb
Make Steep Ruby 2.7/3.0 compatible.
Fixes https://github.com/soutaro/steep/issues/266
> Allow private method call with self

- lib/steep/type_construction.rb
- test/type_construction_test.rb
Fixes https://github.com/soutaro/steep/issues/269
The error was caused by `foo {|(a, b)| }` arguments with invoking non-existent methods.
> Fix UnexpectedError

- lib/steep/type_construction.rb
- lib/steep/type_inference/context.rb
- smoke/implements/b.rb
- smoke/implements/b.rbs
- test/type_construction_test.rb
Fixes https://github.com/soutaro/steep/issues/338
> @implements annotations inside blocks

- lib/steep/services/hover_content.rb
- lib/steep/source.rb
- lib/steep/type_construction.rb
- test/source_test.rb
- test/type_construction_test.rb
This breaks completion/hover in blocks #338
> Fix annotation calculation after `delete_unrelated_defs`

- lib/steep/interface/block.rb
- lib/steep/type_construction.rb
- smoke/regression/issue_372.rb
- smoke/regression/issue_372.rbs
- test/type_construction_test.rb
Fixes https://github.com/soutaro/steep/issues/372
> Passing optional block

- .github/workflows/ruby.yml
* Add 3.0
* Fix 2.7 and 2.6 tags
> Fix ruby versions

- lib/steep/type_construction.rb
- test/type_construction_test.rb
Fixes #389 
I think the source of the problem is assignment inside blocks.
cc/ @pocke
> Type check on lvar assignments

- lib/steep/server/interaction_worker.rb
- lib/steep/services/hover_content.rb
- test/interaction_worker_test.rb
Implement auto complete feature for rbs files
and some fix for hover feature
Demo 
https://user-images.githubusercontent.com/18569016/129554155-d0c7ebcd-8eb3-4669-ad77-68f7b721e28c.mov
> Implement auto complete feature

- lib/steep/diagnostic/ruby.rb
- lib/steep/type_inference/send_args.rb
- smoke/diagnostics/test_expectations.yml
- test/type_construction_test.rb
Thanks to @ksss for reporting the issues. 🙏 
* Closes #405
* Closes #408
Seems like a bug in Diagnostic classes.
> Fix NoMethodError with csend

- lib/steep/type_inference/send_args.rb
- test/type_construction_test.rb
* Add test for https://github.com/soutaro/steep/pull/449
* Delete unused code
> Fix SendArgs

- Gemfile
- Gemfile.lock
* Delete `racc` and `rbs`
* `bundle update`
> Fixup Gemfile

- Gemfile.lock
- steep.gemspec
Reverts soutaro/steep#489
Reverting again to continue working for RBS 2.0 support.
> Revert "Revert "Relax RBS gemspec requirements""

- Gemfile.lock
- lib/steep/ast/types/factory.rb
- lib/steep/ast/types/name.rb
- lib/steep/diagnostic/signature.rb
- lib/steep/signature/validator.rb
- lib/steep/subtyping/variable_variance.rb
- smoke/diagnostics-rbs/nonregular-type-alias.rbs
- smoke/diagnostics-rbs/recursive-type-alias.rbs
- smoke/diagnostics-rbs/test_expectations.yml
- test/test_helper.rb
- test/type_construction_test.rb
- test/type_factory_test.rb
- test/validation_test.rb
> Support generic type aliases

- lib/steep/type_construction.rb
- test/type_construction_test.rb
> Type check return without value

- lib/steep/server/interaction_worker.rb
- lib/steep/services/completion_provider.rb
- lib/steep/services/hover_content.rb
- lib/steep/type_inference/context.rb
* Show docs on hovering a constant
* Show docs on constant completion
* Better method name completion formatting
> Better hover/completion message

- lib/steep/cli.rb
- test/cli_test.rb
`steep binstub` generates `bin/steep` to run Steep after setting up Bundler and rbenv/rvm. The command can be used for LSP integration.
> Add binstub command

- lib/steep/cli.rb
- test/cli_test.rb
* `$REPO_ROOT` is not defined
* Use `readlink` to normalize paths
> Fix binstub

- lib/steep.rb
- lib/steep/shims/filter_map.rb
- test/shim_test.rb
> Add filter_map shim

- lib/steep/type_construction.rb
- test/type_construction_test.rb
> Handle class declaration with non-const super class

- lib/steep/type_construction.rb
- test/type_construction_test.rb
Fixes https://github.com/soutaro/steep/issues/470
> Incompatible default value is a type error

- lib/steep/ast/types/proc.rb
- test/type_construction_test.rb
> Load ChildrenLevel helper in AST::Types::Proc

- test/type_construction_test.rb
Because overrideng test case that added in https://github.com/soutaro/steep/pull/577
https://github.com/soutaro/steep/pull/579#discussion_r895802998
> Fix discarding test_anonymouse_block_forwarding test case

- lib/steep/type_construction.rb
- lib/steep/type_inference/logic_type_interpreter.rb
- lib/steep/type_inference/type_env.rb
- sig/steep/type_inference/logic_type_interpreter.rbs
- sig/steep/type_inference/type_env.rbs
- test/type_construction_test.rb
- test/type_env_test.rb
Related #572 
Fix `TypeEnv#join` so that it correctly handles `#pure_method_calls` and it's invalidations.
> Fix type refinements

- lib/steep/services/hover_provider/ruby.rb
- lib/steep/typing.rb
- sig/steep/services/hover_provider/ruby.rbs
- sig/steep/source.rbs
- sig/steep/typing.rbs
- test/ruby_hover_test.rb
Didn't show the type of the variable...
> Fix hover on multiple assignment

- lib/steep/signature/validator.rb
- test/validation_test.rb
Fixes https://github.com/soutaro/steep/issues/603
> Fix type application validation

- lib/steep.rb
- lib/steep/annotation_parser.rb
- lib/steep/ast/annotation.rb
- lib/steep/ast/assertion.rb
- lib/steep/ast/node/type_assertion.rb
- lib/steep/diagnostic/ruby.rb
- lib/steep/server/lsp_formatter.rb
- lib/steep/services/hover_provider/rbs.rb
- lib/steep/services/hover_provider/ruby.rb
- lib/steep/source.rb
- lib/steep/type_construction.rb
- sig/shims/exception.rbs
- sig/shims/parser.rbs
- sig/shims/parser/comment.rbs
- sig/steep/annotation_parser.rbs
- sig/steep/ast/annotation.rbs
- sig/steep/ast/assertion.rbs
- sig/steep/ast/node/type_assertion.rbs
- sig/steep/diagnostic/ruby.rbs
- sig/steep/server/lsp_formatter.rbs
- sig/steep/services/hover_provider/rbs.rbs
- sig/steep/services/hover_provider/ruby.rbs
- sig/steep/services/hover_provider/singleton_methods.rbs
- sig/steep/source.rbs
- test/cli_test.rb
- test/ruby_hover_test.rb
- test/source_test.rb
- test/type_check_service_test.rb
- test/type_construction_test.rb
Spec: https://hackmd.io/Z6UR_5UlT32JqwOKS21hHg?both
> Add type assertion syntax

- lib/steep.rb
- lib/steep/ast/node/type_application.rb
- lib/steep/ast/node/type_assertion.rb
- lib/steep/ast/types/factory.rb
- lib/steep/diagnostic/helper.rb
- lib/steep/diagnostic/lsp_formatter.rb
- lib/steep/diagnostic/ruby.rb
- lib/steep/diagnostic/signature.rb
- lib/steep/services/signature_service.rb
- lib/steep/source.rb
- lib/steep/type_construction.rb
- lib/steep/type_inference/logic_type_interpreter.rb
- sig/steep/ast/node/type_application.rbs
- sig/steep/ast/node/type_assertion.rbs
- sig/steep/diagnostic/helper.rbs
- sig/steep/diagnostic/lsp_formatter.rbs
- sig/steep/diagnostic/ruby.rbs
- sig/steep/diagnostic/signature.rbs
- sig/steep/range_extension.rbs
- sig/steep/source.rbs
- sig/steep/type_construction.rbs
- sig/steep/type_inference/method_call.rbs
- test/ast/node/type_application_test.rb
- test/source_test.rb
- test/type_construction_test.rb
See [proposal](https://hackmd.io/Z6UR_5UlT32JqwOKS21hHg).
> Add type application syntax

- lib/steep/diagnostic/ruby.rb
- lib/steep/interface/block.rb
- lib/steep/module_helper.rb
- lib/steep/source.rb
- lib/steep/type_construction.rb
- lib/steep/type_inference/block_params.rb
- lib/steep/type_inference/context.rb
- lib/steep/type_inference/method_params.rb
- lib/steep/type_inference/send_args.rb
- sample/lib/conference.rb
- sample/sig/conference.rbs
- sig/shims/parser.rbs
- sig/shims/parser/nodes.rbs
- sig/steep/diagnostic/ruby.rbs
- sig/steep/interface/block.rbs
- sig/steep/module_helper.rbs
- sig/steep/type_construction.rbs
- sig/steep/type_inference/block_params.rbs
- sig/steep/type_inference/context.rbs
- sig/steep/type_inference/method_params.rbs
- sig/steep/type_inference/multiple_assignment.rbs
- sig/steep/type_inference/send_args.rbs
- sig/steep/typing.rbs
- smoke/diagnostics/test_expectations.yml
- test/args_test.rb
- test/method_params_test.rb
- test/type_construction_test.rb
https://github.com/soutaro/steep/issues/336
> Support `...`

- lib/steep/type_construction.rb
- test/type_construction_test.rb
> Let `return` have multiple values

- lib/steep/type_construction.rb
- sig/steep/type_construction.rbs
- smoke/enumerator/a.rb
- smoke/enumerator/b.rb
- smoke/enumerator/test_expectations.yml
- test/type_construction_test.rb
> Infer method return types using hint

- lib/steep/type_construction.rb
- lib/steep/type_inference/block_params.rb
- sig/steep/interface/function.rbs
- sig/steep/type_inference/block_params.rbs
- test/block_params_test.rb
- test/type_construction_test.rb
> Distribute `untyped` to block params

- lib/steep.rb
- lib/steep/drivers/check.rb
- lib/steep/drivers/checkfile.rb
- lib/steep/drivers/stats.rb
- lib/steep/drivers/utils/driver_helper.rb
- lib/steep/drivers/watch.rb
- lib/steep/server/base_worker.rb
- lib/steep/server/master.rb
- lib/steep/server/worker_process.rb
- lib/steep/thread_waiter.rb
- sig/steep/drivers/check.rbs
- sig/steep/project/options.rbs
- sig/steep/server/master.rbs
- sig/steep/server/worker_process.rbs
- sig/steep/thread_waiter.rbs
- test/master_test.rb
Closes #776 
There are two improvements in this PR.
1. Make worker process handling more stable -- avoid possible blocking in main process
2. Validate RBS collection availability in main process to quickly report the problem
> Improve worker process handling

- lib/steep/type_construction.rb
- sig/steep/type_construction.rbs
- test/type_construction_test.rb
> Convert block-pass-arguments with `#to_proc`

- lib/steep/signature/validator.rb
- test/validation_test.rb
> Validate type applications in ancestors

- lib/steep/type_construction.rb
- sig/steep/type_construction.rbs
- smoke/lambda/a.rb
- smoke/lambda/test_expectations.yml
- test/type_check_test.rb
> Give a special typing rule to `#lambda` calls

- lib/steep/drivers/utils/jobs_option.rb
No type check worker runs in the language server on single core computer.
> Ensure at least one type check worker runs

- lib/steep/subtyping/check.rb
- test/type_check_test.rb
> Fix interface type inference

- lib/steep/ast/types/factory.rb
- lib/steep/diagnostic/deprecated/else_on_exhaustive_case.rb
- lib/steep/diagnostic/ruby.rb
- lib/steep/node_helper.rb
- lib/steep/type_construction.rb
- lib/steep/type_inference/logic_type_interpreter.rb
- sig/steep/ast/types/factory.rbs
- sig/steep/diagnostic/deprecated/else_on_exhaustive_case.rbs
- sig/steep/diagnostic/ruby.rbs
- sig/steep/type_inference/logic_type_interpreter.rbs
- smoke/diagnostics/incompatible_annotation.rb
- smoke/diagnostics/test_expectations.yml
- smoke/type_case/test_expectations.yml
- test/logic_type_interpreter_test.rb
- test/type_check_test.rb
- test/type_construction_test.rb
Closes https://github.com/soutaro/steep/issues/783
> Better flow-sensitive typing

- lib/steep/services/hover_provider/ruby.rb
> hover: Fix NoMethodError on generating hover for not supported files

- lib/steep/ast/types/factory.rb
- test/type_check_test.rb
> Unfold type alias on unwrap optional

- lib/steep/type_inference/send_args.rb
- test/type_check_test.rb
> Report `UnexpectedKeywordArgument` even if no keyword param is accepted

- lib/steep/type_construction.rb
- test/type_check_test.rb
> Fix proc type assignment

- lib/steep/services/signature_help_provider.rb
- test/signature_help_provider_test.rb
> Fix UnknownNodeError in SignatureHelp

- lib/steep/server/lsp_formatter.rb
- test/server/lsp_formatter_test.rb
> Let hover show the type of method call node

- lib/steep/type_inference/logic_type_interpreter.rb
- sig/steep/ast/types/factory.rbs
- test/type_check_test.rb
> Filx `nil?` unreachability detection

- lib/steep/source.rb
Related to https://github.com/soutaro/steep/issues/854
Not sure if it works, but this PR avoids using the Parser method that actually raises the error.
> Use RBS::Buffer method to calculate position

- lib/steep/drivers/checkfile.rb
- lib/steep/drivers/stats.rb
- lib/steep/interface/function.rb
- lib/steep/project/dsl.rb
- lib/steep/server/interaction_worker.rb
- lib/steep/subtyping/check.rb
- lib/steep/subtyping/constraints.rb
- lib/steep/type_inference/type_env.rb
This patch reduces the warnings from 255 to 233. Is this helpful?
> Update inline type comments

- lib/steep/type_inference/logic_type_interpreter.rb
- sig/steep/type_inference/logic_type_interpreter.rbs
- test/logic_type_interpreter_test.rb
- test/type_check_test.rb
Unexpected `UnreachableBranch` was reported.
> Fix `nil?` typing with `untyped` receiver

- lib/steep/signature/validator.rb
- test/validation_test.rb
Type alias validation with module alias raised an error.
> Fix type alias validation

- lib/steep/type_construction.rb
- test/type_check_test.rb
Closes https://github.com/soutaro/steep/issues/914
> Let `[]=` call have correct type

- lib/steep/type_construction.rb
- test/type_check_test.rb
Closes https://github.com/soutaro/steep/issues/913
> Test if a parameter is `_`

- sig/steep/subtyping/check.rbs
Before:
```
Detected 166 problems from 25 files
```
After:
```
Detected 155 problems from 25 files
```
> Update Steep::Subtyping::Check#check types

- lib/steep/server/interaction_worker.rb
- lib/steep/services/completion_provider.rb
- sig/steep/services/completion_provider.rbs
- test/completion_provider_test.rb
> Implement completion for comments

- Gemfile.lock
- lib/steep/ast/types/factory.rb
- lib/steep/ast/types/proc.rb
- lib/steep/interface/block.rb
- lib/steep/interface/function.rb
- lib/steep/interface/method_type.rb
- lib/steep/server/lsp_formatter.rb
- lib/steep/services/completion_provider.rb
- lib/steep/services/signature_help_provider.rb
- lib/steep/subtyping/check.rb
- lib/steep/subtyping/variable_variance.rb
- lib/steep/type_construction.rb
- lib/steep/type_inference/block_params.rb
- lib/steep/type_inference/logic_type_interpreter.rb
- lib/steep/type_inference/method_params.rb
- lib/steep/type_inference/send_args.rb
- sig/steep/ast/types/factory.rbs
- sig/steep/interface/function.rbs
- sig/steep/services/signature_help_provider.rbs
- sig/steep/subtyping/variable_variance.rbs
- sig/steep/type_inference/block_params.rbs
- sig/steep/type_inference/method_params.rbs
- steep.gemspec
- test/type_check_test.rb
- test/type_factory_test.rb
Implement https://github.com/ruby/rbs/issues/1335.
> Implement untyped function params

- doc/narrowing.md
> Fix typo in narrowing.md

- lib/steep.rb
- lib/steep/drivers/check.rb
- lib/steep/drivers/checkfile.rb
- lib/steep/drivers/stats.rb
- lib/steep/drivers/utils/driver_helper.rb
- lib/steep/drivers/watch.rb
- lib/steep/server/custom_methods.rb
- lib/steep/server/delay_queue.rb
- lib/steep/server/interaction_worker.rb
- lib/steep/server/master.rb
- lib/steep/server/type_check_worker.rb
- sig/steep/drivers/stats.rbs
- sig/steep/drivers/utils/driver_helper.rbs
- sig/steep/server/custom_methods.rbs
- sig/steep/server/delay_queue.rbs
- sig/steep/server/master.rbs
- sig/steep/server/type_check_worker.rbs
- sig/steep/services/stats_calculator.rbs
- test/interaction_worker_test.rb
- test/master_test.rb
- test/type_check_worker_test.rb
This makes detecting the finish of type checking simpler.
> Make type checking a LSP request, not a LSP notification

- .github/dependabot.yml
Updating dependabot config because it hasn't update `/Gemfile` for months...
> Add `versioning-strategy`

- lib/steep.rb
- lib/steep/diagnostic/ruby.rb
- lib/steep/drivers/checkfile.rb
- lib/steep/interface/function.rb
- lib/steep/services/type_check_service.rb
- lib/steep/signature/validator.rb
- lib/steep/subtyping/check.rb
- lib/steep/type_inference/block_params.rb
- lib/steep/type_inference/context.rb
- lib/steep/type_inference/type_env.rb
- lib/steep/type_inference/type_env_builder.rb
- sig/steep/project/dsl.rbs
This reduces type errors and warnings from 60 to 37.
Is this needed?
> Add type comments

- lib/steep/server/master.rb
Cherry pick https://github.com/soutaro/steep/pull/1285/commits/4e4312eee7a8260a7b3e1defdd01d6473259a128
> Ignore `didChangeWatchedFiles notification` for open files

- lib/steep/server/master.rb
- lib/steep/type_construction.rb
- sig/shims/language-server_protocol.rbs
- sig/steep/type_construction.rbs
- test/type_check_test.rb
* #1300 fixes worker crash on deleting files
* #1299 fixes untyped hash typing
> Backports #1300 and #1299

- test/test_helper.rb
> Print test names in CI for investigation

- lib/steep/ast/ignore.rb
- lib/steep/diagnostic/signature.rb
- lib/steep/drivers/diagnostic_printer.rb
- lib/steep/services/hover_provider/ruby.rb
- lib/steep/services/signature_help_provider.rb
- lib/steep/source.rb
- lib/steep/subtyping/check.rb
- lib/steep/type_inference/block_params.rb
- lib/steep/type_inference/type_env.rb
47 -> 22
Note: This contains https://github.com/soutaro/steep/pull/1286
> refactor: Use Array#fetch instead of Array#[] to resolve type errors

- lib/steep/diagnostic/ruby.rb
- lib/steep/type_construction.rb
- sig/steep/diagnostic/ruby.rbs
- test/type_check_test.rb
- test/type_construction_test.rb
> Emit SingletonTypeMismatch when class/module mismatch

- lib/steep/diagnostic/ruby.rb
- lib/steep/type_construction.rb
- manual/ruby-diagnostics.md
- sig/steep/diagnostic/ruby.rbs
- smoke/hash/test_expectations.yml
- test/type_check_test.rb
Closes https://github.com/soutaro/steep/issues/1046
> Report diagnostic on unknown record key

- lib/steep/diagnostic/lsp_formatter.rb
- test/master_test.rb
> Add link to diagnostic manual

- lib/steep/type_construction.rb
- sig/steep/type_inference/send_args.rbs
- test/type_check_test.rb
Closes https://github.com/soutaro/steep/pull/1382, https://github.com/soutaro/steep/issues/1086
> Skip type checking forwarded argument if the method is undeclared

- lib/steep/source.rb
- lib/steep/type_construction.rb
- sig/steep/type_construction.rbs
- sig/test/source_test.rbs
- sig/test/type_check_test.rbs
- test/source_test.rb
- test/type_check_test.rb
`@type block: T` annotations didn't work.
> Fix block type checking
