soutaro/steep

bin/smoke_runner.rb, lib/steep/interface.rb, lib/steep/parser.y, lib/steep/signature/class.rb, lib/steep/signature/errors.rb, lib/steep/signature/interface.rb, lib/steep/type_assignability.rb, lib/steep/type_construction.rb, lib/steep/type_name.rb, lib/steep/types/name.rb, smoke/class/a.rbi, smoke/class/d.rb, smoke/class/e.rb, smoke/class/f.rb, smoke/initialize/a.rb, smoke/initialize/a.rbi, stdlib/builtin.rbi, test/signature_class_test.rb, test/signature_parsing_test.rb, test/test_helper.rb, test/type_assignability_test.rb, test/type_parsing_test.rb
In Ruby, object instantiation is done by a normal method call to `new`. This prevents subtyping relations from holding between any two classes which do not have compatible `initialize` types.
The following is an example: `B.class` is not a subtype of `A.class`, and `B` is not a subtype of `A` because of `Object#class`.
```
class A
def initialize: (Integer) -> any
end
class B <: A
def initialize: (String) -> any
end
```
Clearly, this does not match with the intuition of most Rubyists.
To fix this issue, we would like to introduce an idea of *constructor*.
* Class types can be attributed with `constructor` or `noconstructor` keywords
* `constructor` class types have `.new` method
* `noconstructor` class types do not have `.new` method
* Method definitions can be attributed with …
=> Constructor typing

lib/steep/ast/annotation.rb, lib/steep/ast/signature/env.rb, lib/steep/drivers/check.rb, lib/steep/interface/builder.rb, lib/steep/parser.y, lib/steep/type_construction.rb, smoke/class/g.rb, smoke/module/a.rbi, smoke/module/d.rb, smoke/module/e.rb, test/annotation_parsing_test.rb, test/type_construction_test.rb
Currently, when you want to type check your Ruby programs, you need `@implements` annotations to all of your classes/modules. This patch is to decrease the efforts you need to start type checking. 🎉 
1. When your program contains a module or a class, and
2. If the module/class does not have `@implements` annotation, and
3. If  a signature which has the same name exists, then
4. It inserts `@implements` annotation automatically
Not implemented yet:
* Support for nested modules/classes
* Support for parametrized signatures
=> Auto implements

lib/steep/parser.y
`\w` contains `_`. So Onigumo warns.
```bash
$ RUBYOPT= ruby -w -e "/[\w_]/" 2>&1
-e:1: warning: character class has duplicated range: /[\w_]/
-e:1: warning: possibly useless use of a literal in void context
```
This change removes the `_`.
=> Remove duplicated range of regexp

README.md, steep.gemspec
I guess steep support only Ruby 2.5, because steep uses `yield_self`, and it's tested only Ruby 2.5 on Travis CI.
=> Support Ruby 2.5

bin/smoke_runner.rb, lib/steep/errors.rb, lib/steep/interface/instantiated.rb, lib/steep/interface/method_type.rb, lib/steep/subtyping/check.rb, lib/steep/type_construction.rb, smoke/class/a.rb, smoke/method/a.rb, smoke/method/a.rbi, smoke/method/b.rb, test/subtyping_test.rb, test/type_construction_test.rb
It now checks:
* If signature's method type is overloaded
* If annotation is compatible with signature's definition
=> Fix method typing check

lib/steep/type_construction.rb, smoke/ensure/a.rb, smoke/kwbegin/a.rb, smoke/rescue/a.rb
This pull-request makes Steep to support `begin - rescue - end` syntax.
=> Add support error handling sytnax (`begin - rescue - end`)

lib/steep.rb, lib/steep/ast/annotation.rb, lib/steep/ast/types/helper.rb, lib/steep/ast/types/intersection.rb, lib/steep/ast/types/union.rb, lib/steep/cli.rb, lib/steep/drivers/annotations.rb, lib/steep/drivers/check.rb, lib/steep/errors.rb, lib/steep/source.rb, lib/steep/subtyping/result.rb, lib/steep/type_construction.rb, lib/steep/type_inference/type_env.rb, smoke/rescue/a.rb, test/constraints_test.rb, test/source_test.rb, test/subtyping_test.rb, test/test_helper.rb, test/type_construction_test.rb, test/type_env_test.rb, test/type_test.rb
This PR implements branch sensitive typing such that type annotations and local variable type inference works take care of branching.
```rb
x = nil
if test()
y = x + 1  # Type of x is Integer
else
y = (x + "").length # Type of x is String
end
```
It works for `rescue` and while loops.
It also works for local variables assignment type inference like:
```rb
if test()
x = 30
y = x + 1
else
x = "foo"
y = (x + "").length
end
```
* Global variable annotation
=> Branch sensitive typing

lib/steep/errors.rb, lib/steep/source.rb, lib/steep/subtyping/result.rb, lib/steep/type_construction.rb, lib/steep/type_inference/type_env.rb, smoke/type_case/a.rb, test/source_test.rb, test/test_helper.rb, test/type_construction_test.rb, test/type_env_test.rb
This patch is to support typing based on `case` expression:
```rb
x = nil
case x
when Integer
y = x + 1
when String
y = x + ""
else
y = x.id2name
end
```
This patch assumes the implementation of `Class#===`, so this behavior may become opt-in.
* When `case` is on a *value* expression (current implementation only supports `lvar`), and
* `when` clauses have all `*.class` types, then
* `when` body will have an instance of that types (or their union), and
* `else` body will have an instance of left type (or their union)
* To support assignments like: `case (x = foo)`
* To support other kinds of variables: constants, ivars, gvars
=> Implement trivial typecase for `case` expression

lib/steep/ast/types/name.rb, lib/steep/interface/abstract.rb, lib/steep/interface/builder.rb, lib/steep/parser.y, lib/steep/subtyping/check.rb, lib/steep/type_construction.rb, smoke/enumerator/b.rb, stdlib/builtin.rbi, test/subtyping_test.rb, test/test_helper.rb, test/type_construction_test.rb
This fixes typing of `Array` constant. `Array` is a parametrized type but what about `.class` type???
* Let `.class` types be non-parametrized
* Let `instance` types in `.class` types with with `any` application
=> Fix Array typing

lib/steep/errors.rb, lib/steep/interface/method_type.rb, lib/steep/subtyping/check.rb, lib/steep/type_construction.rb, test/subtyping_test.rb, test/type_construction_test.rb
Improve type case for parametrized types. It also checks if `else` clause present in the exaustive case.
```rb
x = nil
case x
when Array
y = x[0]
when Symbol
z = x
else
end
```
=> Improve type case

lib/steep/ast/signature/members.rb, lib/steep/errors.rb, lib/steep/interface/builder.rb, lib/steep/interface/instantiated.rb, lib/steep/interface/method.rb, lib/steep/parser.y, lib/steep/type_construction.rb, smoke/class/i.rb, smoke/class/i.rbi, test/interface_builder_test.rb, test/signature_parsing_test.rb
A method is *incompatible* if it's type is not a subtype of that method of the super class.
```
class Super
def foo: (Object) -> Integer
end
class Child <: Super
def (incompatible) foo: () -> String
end
```
In this case, `Child` is not a subtype of `Super`, and this kind of inheritance cannot be typed. Steep cannot check if this inheritance breaks nothing, but it allows to user to annotate `incompatible` to let this bypass type checking.
This also allows `super` calls in `initialize` method definitions.
=> Introduce *incompatible* method

lib/steep/ast/method_type.rb, lib/steep/interface/builder.rb, lib/steep/interface/method.rb, lib/steep/interface/method_type.rb, lib/steep/parser.y, lib/steep/subtyping/check.rb, lib/steep/type_construction.rb, smoke/block/c.rb, smoke/block/c.rbi, test/signature_parsing_test.rb, test/type_construction_test.rb
There has been no way to type check overloaded methods with optional blocks.
```
class Foo
def bar: () -> Integer
| <'a> { () -> 'a } -> 'a
end
```
Now, you can type check the method with in-line method type annotation.
```rb
class Foo
def bar
if block_given?
yield
else
30
end
end
end
```
Steep now allows writing an *optional block* in method type explicitly, not as a overloading. You can use the `?`-prefixed block type to annotate methods in your Ruby code.
Note that Steep does not provide any support if `yield` can work or not. Checking if a block is given before `yield` in that methods is your responsibility. 😢
=> Improve typing of optional blocks

lib/steep/ast/annotation.rb, lib/steep/ast/annotation/collection.rb, lib/steep/drivers/check.rb, lib/steep/source.rb, lib/steep/type_construction.rb, lib/steep/type_inference/block_params.rb, lib/steep/type_inference/type_env.rb, smoke/class/c.rb, smoke/class/e.rb, smoke/implements/a.rb, test/annotation_collection_test.rb, test/block_params_test.rb, test/source_test.rb, test/type_construction_test.rb, test/type_env_test.rb
This patch makes types from `Annocation::Collection` be *absolute*. This allows deleting scattered `absolute_type` calls from `TypeConstruction`. This also allows subtyping checks to skip structural comparison caused by mixed *absolute*/*relative* type names, which sometimes caused a huge performance hit.
=> Refactor Annotation::Collection

steep.gemspec
Hi! 😃 
This makes Steep available also in Rails 5.2.
Reproduction
------------
1. Edit `Gemfile`.
```diff
+gem 'steep'
```
2. Run `bundle install` command.
```
$ bundle install
Fetching gem metadata from https://rubygems.org/.........
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Bundler could not find compatible versions for gem "activesupport":
In snapshot (Gemfile.lock):
activesupport (= 5.2.1)
In Gemfile:
rails (~> 5.2.1) was resolved to 5.2.1, which depends on
activesupport (= 5.2.1)
steep was resolved to 0.5.0, which depends on
activesupport (~> 5.1.0)
Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.
Bundler could not find compatible versions for gem "steep":
In …
```
=> Fix ActiveSupport version

lib/steep.rb, lib/steep/parser.y, smoke/class/i.rbi, stdlib/builtin.rbi, test/block_params_test.rb, test/constant_env_test.rb, test/constraints_test.rb, test/interface_builder_test.rb, test/signature_parsing_test.rb, test/subtyping_test.rb, test/test_helper.rb, test/type_construction_test.rb, test/type_parsing_test.rb
Now Steep allows writing `<` for class inheritance, not `<:`.
* When you write `<:` it prints a warning message.
=> Update signature syntax

lib/steep/subtyping/check.rb, lib/steep/type_construction.rb, smoke/hash/d.rb, smoke/hash/e.rb, smoke/hash/e.rbi, test/subtyping_test.rb, test/type_construction_test.rb
Type inference for type variables inside *Hash* type is now supported.
```
class Foo
def get: <'a> ({ foo: 'a }) -> 'a
end
```
```rb
Foo.new.get({ foo: 3 })       # : Integer
```
=> Fix hash typing

lib/steep/cli.rb
This PR adds a new `steep version` subcommand, which only outputs the Steep version to STDOUT.
E.g.
```
$ steep version
0.7.0
```
=> Add `steep version` subcommand

lib/steep/errors.rb, lib/steep/interface/method_type.rb, lib/steep/type_construction.rb, lib/steep/type_inference/send_args.rb, smoke/literal/b.rb, test/args_test.rb, test/type_construction_test.rb
This fixes keyword typing to correctly type check the following example.
```
class A
def foo: (any, ?foo: any) -> void
end
```
and
```rb
A.new.foo({ foo: 3 })
```
=> Fix keyword typing

smoke/regexp/a.rb, smoke/regexp/b.rb, stdlib/builtin.rbi
This PR updates built-in types `Regexp` and `MetaData`.
- `Regexp`:
- Add missing methods.
- API Doc: http://ruby-doc.org/core-2.5.1/Regexp.html
- `MatchData`:
- Add class and methods.
- API Doc: http://ruby-doc.org/core-2.5.1/MatchData.html
- `Encoding`:
- `Regexp#encoding` requires `Encoding` type.
- API Doc: http://ruby-doc.org/core-2.5.1/Encoding.html
=> Update built-in types: `Regexp`, `MatchData`

lib/steep/cli.rb
This PR adds a new option `--version` (`-v`), which only outputs the Steep version to STDOUT.
E.g.
```
$ steep --version
steep 0.7.0
$ steep -v
steep 0.7.0
```
=> Add option to show Steep's version

Gemfile, lib/steep/cli.rb, test/gem_cli_test.rb, test/gems/with_steep_types/lib/with_steep_types.rb, test/gems/with_steep_types/sig/with_steep_types.rbi, test/gems/with_steep_types/with_steep_types.gemspec, test/test_helper.rb
This PR is to allow shipping type definitions in gems. For this, gem developers and steep users should follow the protocol below.
Put `*.rbi` files in a directory and ship them in the gem. And put a key/value pair `"steep_types" => signature_dir` in `metadata` of its gemspec.
```rb
spec.metadata = { "steep_types" => "sig" }
```
We recommend using `sig` as the name of the directory to have type definitions, but you can use any directory.
Run Steep with `-G` option, which accepts gem name `strong_json` or with version `strong_json:1.2.3`.
```
$ steep check -G strong_json -G other_gem -G another_gem lib
```
When you are using with bundler, `steep` detect that and load types from bundled gems automatically.
```
$ bundle exec steep check lib
```
`steep` also has `paths` subcommand, which print …
=> Load types from gems

Gemfile, lib/steep/cli.rb, test/gem_cli_test.rb, test/gems/without_steep_types/lib/without_steep_types.rb, test/gems/without_steep_types/without_steep_types.gemspec
Revise two error message.
When specified gem cannot be found:
```
Gem not found: name=rake1, version=
```
When specified gem does not provide type definition:
```
Type definition directory not found: gem=rake, version=10.5.0
```
=> Report error if -G gem does not provide “steep_types”

lib/steep/cli.rb, test/gem_cli_test.rb
Fix type checking when developing a rubygem.
Because steep detects bundled gem signatures, the signatures of the developing gem loaded twice. Use `#uniq` to solve this issue.
=> Unique signature paths

lib/steep/subtyping/trace.rb, lib/steep/type_construction.rb, lib/steep/type_inference/block_params.rb, test/test_helper.rb
```
% RUBYOPT="-w" bundle exec rake test 2>&1 | grep interpreted
/home/sei/src/github.com/soutaro/steep/test/test_helper.rb:277: warning: `*' interpreted as argument prefix
/home/sei/src/github.com/soutaro/steep/lib/steep/subtyping/trace.rb:40: warning: `*' interpreted as argument prefix
/home/sei/src/github.com/soutaro/steep/lib/steep/type_construction.rb:175: warning: `*' interpreted as argument prefix
/home/sei/src/github.com/soutaro/steep/lib/steep/type_inference/block_params.rb:42: warning: `*' interpreted as argument prefix
/home/sei/src/github.com/soutaro/steep/lib/steep/type_inference/block_params.rb:43: warning: `*' interpreted as argument prefix
/home/sei/src/github.com/soutaro/steep/lib/steep/type_inference/block_params.rb:45: warning: `*' interpret …
```
=> Fix interpreted as argument prefix warning

smoke/integer/a.rb, stdlib/builtin.rbi
This PR adds the type definition of `Kernel.#Integer` method.
Please see API documentation: <http://ruby-doc.org/core-2.5.3/Kernel.html#method-i-Integer>
In addition, some types are added for smoke tests.
- `_ToI` (`interface`)
- `_ToInt` (`interface`) - see https://github.com/soutaro/steep/pull/71#discussion_r230157794
- ~~`Time` (implements `_ToI` interface)~~
- Instead, add `WithToI` class for test
- `String#to_i` method
- http://ruby-doc.org/core-2.5.3/String.html#method-i-to_i
Further, `Object#to_i` definition is removed, because `Object` doesn't have `to_i` method.
See also <http://ruby-doc.org/core-2.5.3/Object.html>.
=> Add `Kernel.#Integer` method's type definition

lib/steep/ast/namespace.rb
```
% bin/console
irb(main):001:0> Steep::AST::Namespace.empty.hash
Traceback (most recent call last):
3: from bin/console:14:in `<main>'
2: from (irb):1
1: from /home/sei/src/github.com/soutaro/steep/lib/steep/ast/namespace.rb:59:in `hash'
NoMethodError (undefined method `hath' for Steep::AST::Namespace:Class)
Did you mean?  hash
```
```
% bin/console
irb(main):001:0> Steep::AST::Namespace.empty.hash
=> 653728956248800086
```
=> Fix typo hath -> hash

lib/steep/type_construction.rb, smoke/skip/skip.rb
Steep skips type checking right-hand side of an assignment to `__skip__`. This can be used to workaround writing Ruby code with an unsupported syntax.
Also introducing `__any__` for more descriptive *cast*.
```rb
__skip__ = begin
def object.foo
end
end
```
=> Allow skipping type checking

lib/steep/ast/signature/members.rb, lib/steep/drivers/utils/validator.rb, lib/steep/interface/abstract.rb, lib/steep/interface/builder.rb, lib/steep/interface/instantiated.rb, lib/steep/interface/method.rb, lib/steep/parser.y, lib/steep/subtyping/check.rb, lib/steep/type_construction.rb, smoke/initialize/a.rb, test/interface_builder_test.rb, test/signature_parsing_test.rb, test/subtyping_test.rb, test/type_construction_test.rb, test/validation_test.rb
Private method can be declared as:
```
class Foo
def (private) foo: () -> void
end
```
Only a method call without receiver can call the `foo` method.
```rb
class Foo
def foo; end
def bar
foo()      # ok
self.foo() # NoMethod error
end
end
```
Steep validates type definition not to have a method definition override from public to private.
* You have to write `private` to all private methods
* If you don't write `private`, the method is *public*
=> Support private

lib/steep/ast/signature/members.rb, lib/steep/interface/builder.rb, lib/steep/parser.y, stdlib/builtin.rbi, test/interface_builder_test.rb, test/signature_parsing_test.rb
`alias` allows defining an alias of method definition.
```
class Array<'a>
def map: <'x> { ('a) -> 'x } -> Array<'x>
alias collect map
end
```
We don't have to repeat the `map` method types, which may be very long, to define the type of `collect`. The aliasing is for interface method type level:
* `super` information is not passed to `alias` method
* Other attributes are copied
=> Add `alias` signature member

lib/steep/names.rb
`@absolute` was renamed at 5000a506dd1be641819059db9ad0d18904a492f0
=> Fix Steep::Names::Base#hash

lib/steep/ast/method_type.rb, lib/steep/interface/builder.rb, lib/steep/parser.y, smoke/extension/e.rb, smoke/extension/e.rbi, test/interface_builder_test.rb, test/signature_parsing_test.rb
Some library providing `Number` like class extends existing numeric classes to allow binary operators to accept the new class.
```rbi
class MyFloat
def +: (MyFloat) -> MyFloat
| (Integer) -> MyFloat
| (Float) -> MyFloat
end
extension Integer (MyFloat)
def +: (MyFloat) -> MyFloat
| 🤔  # What to write here??? Other libraries may extend Integer#+ too.
end
```
This patch is to allow writing `super` here which means existing method types.
=> `super` in method type definition

lib/steep/type_construction.rb, test/type_construction_test.rb
This PR fixes typing of `||` node.
```rb
x = nil
y = x || []   # The type of `y` is `Array<any>`, but we want it to be `Array<Integer>`
```
=> Use hint for `or` node typing

lib/steep.rb, lib/steep/cli.rb, lib/steep/drivers/langserver.rb, lib/steep/project/file.rb, steep.gemspec, test/langserver_test.rb
This PR introduces a new command `steep langserver`. This server communicates with a client via stdio according to the specification of [Language Server Protocol v3.14.0](https://microsoft.github.io/language-server-protocol/specification).
As a first step, this experimental implementation only supports diagnostics at file change and open. This behavior has been confirmed with [VSCode](https://github.com/wata727/vscode-steep-lsc) and [RubyMine](https://github.com/gtache/intellij-lsp), and you can try it immediately.
This implementation is highly inspired by [language_server-ruby](https://github.com/mtsmfm/language_server-ruby). Therefore, this PR adds [language_server-protocol-ruby](https://github.com/mtsmfm/language_server-protocol-ruby) as a new dependency. This library defines the LSP …
=> Experimental Language Server Protocol support

.gitignore, lib/steep.rb, lib/steep/cli.rb, lib/steep/drivers/check.rb, lib/steep/drivers/validate.rb
Steep now accepts `--log-level` and `--log-output` command line options, which helps to debug language server implementation. 💪
=> Fix logging

lib/steep/type_construction.rb, test/type_construction_test.rb
For #84, just skip the typing of `alias` node for now. Typing may be possible, but skips for now.
=> Skip alias on typing

steep.gemspec
It seems that the rainbow 3.0.0 is compatible with 2.2.2 for ruby >= 2.5.0 (steep required).
Changelog: https://github.com/sickill/rainbow/blob/master/Changelog.md#300-2017-11-29
https://rubygems.org/gems/rainbow
=> Relax rainbow dependency

lib/steep/ast/types/factory.rb, lib/steep/type_construction.rb, lib/steep/type_inference/type_env.rb, test/type_construction_test.rb, test/type_env_test.rb
* Let type of `self` be `self`
* Fix method call
* Fix subtyping
* Expand `self` before checking subtyping relation so that `self` <: `T` holds if _self_type_ <: `T`.
=> Fix self typing

lib/steep/drivers/langserver.rb, test/langserver_test.rb, test/lsp_double.rb, test/test_helper.rb
I found `LangserverTest#test_did_change` failed on my new iMac. I'm not very sure why it happens only on my new computer, but anyway it fails.
So, I add new abstraction to make LSP test more stable, easier, and more reliable. `LSPDouble` objects can be used as a client to langserver. You can write operations from a LSP client and write tests about the status of LSP client.
=> Revise LSP test

lib/steep/interface/method.rb, lib/steep/signature/errors.rb, lib/steep/signature/validator.rb, test/validation_test.rb
Steep does not validate overridden methods compatibilities. Since it involves too many type errors from Ruby standard libraries, like `Object#select` vs `Enumerable#select` vs `Hash#select`...
=> No inheritance validation

lib/steep/type_construction.rb
I'd like to save Steep's output to a file to review them. But if I execute `steep check > out`, the `out` also contains many stack traces.
This pull request will split the stack traces to $stderr.
=> Print stacktrace to stderr instead of stdout

lib/steep.rb, lib/steep/cli.rb, lib/steep/drivers/vendor.rb, lib/steep/project/dsl.rb, lib/steep/project/options.rb, lib/steep/project/target.rb, test/steepfile_test.rb, test/vendor_test.rb
`steep vendor` command copies all of the related signatures, from standard library and bundled gems, to `vendor/sigs` directory. You can check in the directory content to your git repository, and edit them if you need.
```
$ steep vendor              # Vendors in vendor/sigs
$ steep vendor some/where   # Vendors in another location
```
You can access the vendored signatures through `vendor` command in `Steepfile`.
```rb
target :app do
check "app"
ignore "app/views"
vendor             # Equivalent to: vendor "vendor/sigs"
...
end
```
=> Add `steep vendor` command

lib/steep/type_construction.rb, smoke/module/c.rb, test/test_helper.rb, test/type_construction_test.rb, test/type_factory_test.rb
The type of module itself was `Module & singleton(:FooModule)`, which cannot be resolved to interface and method types. This caused the problem of typing singleton methods of the module.
This patch gives the module itself `singleton(:FooModule)`, which includes `Module` in its *ancestors*.
=> Fix self typing in module

lib/steep/type_construction.rb, test/type_construction_test.rb
When steep is trying to type check method calls on `self` type, it reports error message. The message was too verbose and this PR is trying to streamline the output.
=> Fix unknown self typing

exe/rbs, exe/ruby-signature
So that users can run the ruby-signature commands:
```
$ bundle exec rbs
$ bundle exec ruby-signature
```
=> Add exe/rbs and exe/ruby-signature

lib/steep/annotation_parser.rb, test/annotation_parsing_test.rb
To allow annotations like:
```rb
```
=> Relax method name syntax in annotation

lib/steep/ast/builtin.rb, lib/steep/type_construction.rb, test/type_construction_test.rb
Let control-flow operators like `return` and `break` have `bottom` type. This change allows the type checker to reason more about control-flow.
=> Let jumps have bottom type

lib/steep/type_construction.rb, lib/steep/type_inference/type_env.rb, test/type_construction_test.rb, test/type_env_test.rb
* Drop methods related to local variables from `TypeEnv`
* Fix `opasgn` typing
=> Clean type env

lib/steep/type_construction.rb, test/type_construction_test.rb
Method optarg/kwoptard type check didn't use method type as a hint, which caused a `FallbackAny` error with the following code.
```rb
def foo(array = [])
end
```
This PR fixes the issue.
=> Type check optarg with hint

lib/steep/type_inference/context_array.rb, lib/steep/typing.rb, test/context_array_test.rb, test/type_construction_test.rb
Heredoc breaks our assumption about relations between context ranges.
```rb
a = foo(<<EOF)       # [].map { } is sub node of foo call, but the location is not. 🤔 
#{ [].map { } }
EOF
puts a
```
This PR is to introduce tree structure to manage the contexts and to makes context insertions more flexible.
=> Support Heredoc

lib/steep/project/hover_content.rb, test/project_test.rb
If a method is not defined in signature, skip showing hover on it.
=> Fix hover on def

lib/steep/project/file.rb, lib/steep/server/code_worker.rb, lib/steep/type_construction.rb, lib/steep/type_inference/constant_env.rb, lib/steep/type_inference/context.rb, steep.gemspec, test/code_worker_test.rb, test/constant_env_test.rb, test/test_helper.rb, test/type_construction_test.rb, test/type_env_test.rb
Fix broken constant lookup through outer module definition.
```rb
class A::B
C = foo()        # Fixed to resolve to A::B::C
B.bar()          # Fixed to resolve to A::B
end
```
=> Fix constant resolution

lib/steep.rb, steep.gemspec
Steep no longer uses the gem, which was used in `steep watch` command. 👋
=> Remove Pry 🙏 

lib/steep/type_construction.rb, test/type_construction_test.rb
Array and Hash typing were broken. The `synthesize` for their elements should pass type _hints_.
=> Fix typing of union collections

lib/steep/drivers/check.rb, lib/steep/project/options.rb, lib/steep/server/code_worker.rb, test/code_worker_test.rb
This caused a problem that `steep check` and `steep watch` generate different error messages. 😢
=> Filter error messages based on options in LSP

steep.gemspec
Thanks for releasing rbs v0.4.0 :tada:
But unfortunately, I couldn't use it because steep restricts rbs version. So this pull request relaxes the restriction to allow rbs v0.4.0.
I guess steep will work well with rbs v0.4.0 because `rake test` passes.
=> Allow rbs v0.4

lib/steep.rb
Steep langserver uses uri library but it isn't required.
```bash
$ git grep URI
lib/steep/drivers/watch.rb:              uri = URI.parse(response[:params][:uri])
lib/steep/server/code_worker.rb:            uri: URI.parse(project.absolute_path(path).to_s).tap {|uri| uri.scheme = "file"},
lib/steep/server/code_worker.rb:            paths = request[:params][:arguments].map {|arg| source_path(URI.parse(arg)) }
lib/steep/server/code_worker.rb:          path = source_path(URI.parse(request[:params][:textDocument][:uri]))
lib/steep/server/interaction_worker.rb:          uri = URI.parse(request[:params][:textDocument][:uri])
lib/steep/server/interaction_worker.rb:          uri = URI.parse(params[:textDocument][:uri])
lib/steep/server/master.rb:          uri = …
```
=> Add "require 'uri'" for LSP

lib/steep/project/completion_provider.rb, lib/steep/server/interaction_worker.rb, test/completion_provider_test.rb
* This ensures that methods defined on a class / module are returned
earlier in the LSP method autocomplete
* The rationale being the assumption that the most used methods are the ones
defined in the class rather than inherited ones.
* A _*future*_ improvment might make this sort by proximity to the current class,
e.g. `class One < Two < Three` could return the methods defined in the source of `One`,
then the methods defined in the source of `Two`, and then `Three`.
=> Sort methods in LanguageServer to return non-inherited methods first

lib/steep/project/file_loader.rb
This pull request sorts the result of Pathname#glob.
Because Pathname#glob's order depends on the environment.
See https://bugs.ruby-lang.org/issues/8709
The not sorted paths introduce confusing behavior. Steep may display different results with not-sorted paths between different environments.
So I think it it better if the paths are sorted. 
By the way, I found the not-sorted paths with a confusing behavior of steep, I guess it is a bug. So I'll report it as another issue.
=> Sort result of Pathname#glob

lib/steep/project/dsl.rb, lib/steep/project/options.rb, test/steepfile_test.rb
Example:
```rb
target :lib do
typing_options :strict,
allow_missing_definitions: true,
allow_fallback_any: true
end
```
=> Allow typing_options DSL to specify each option

lib/steep/project/completion_provider.rb, test/completion_provider_test.rb
* initialize is a special method in ruby that developer
wouldn't call on an instance of a class, so let's remove
it for the autocomplete provided to LSP
=> Don't autocomplete initialize

lib/steep/type_construction.rb, lib/steep/typing.rb, test/type_construction_test.rb
```ruby
class WithSingleton
class <<self
def open
yield new()
end
end
end
x = Object.new
class <<x
def foo
"foo!"
end
end
```
=> Support singleton class definition

lib/steep/subtyping/check.rb, smoke/class/a.rbs, smoke/class/f.rb, steep.gemspec, test/subtyping_test.rb, test/test_helper.rb, test/type_construction_test.rb
The subtyping relationship between class/module types is now defined with inheritance/mixin relationships (nominal subtyping). (Subtyping between interface types is still defined structurally.)
```rb
class A
def hello: (String) -> void
end
class B < A
end
class C < A
def hello: (Integer) -> void
end
a = b     # Ok
a = c     # Ok even though hello types are incompatible (was an error). Because incompatible methods are so common in Ruby.
b = c     # Error while they are compatible structurally (was ok).
```
=> Nominal Subtyping

lib/steep/project/target.rb, test/target_test.rb
Probably it fixes #158
Steep exits with status code 1 unexpectedly. The cause is type-checking options. 
Steep CLI filters type errors by this option.
https://github.com/soutaro/steep/blob/33f507b4d520859b6df60a186c6c6de78967174f/lib/steep/drivers/check.rb#L56
But the option does not affect the exit status code.
Becuase it checks `target.errors.empty?` but `target.errors` contains unreported type errors.
https://github.com/soutaro/steep/blob/33f507b4d520859b6df60a186c6c6de78967174f/lib/steep/drivers/check.rb#L67
Remove unreported type errors from `Steep::Project::Target#errors`.
=> Make exit code success when Steep has unreported type errors

lib/steep/project/target.rb, test/target_test.rb
Currently Steep ignores signature if the pattern starts with `./`.
For example:
```ruby
target :app do
signature './sig' # it doesn't work
end
```
Because `Steep::Project::Target.test_pattern` receives a relative path, and the relative path doesn't include `./`. So they never match.
Remove `./` from patterns.
=> Allow `./` prefix for signature pattern

lib/steep/ast/types/literal.rb, lib/steep/subtyping/check.rb, lib/steep/type_construction.rb, test/subtyping_test.rb, test/test_helper.rb, test/type_construction_test.rb
@tadd reported a case that returning `false` in a method with type of `String | false` got a type error while we are expecting no error for it.
```ruby
def read_string
return false if has_value?
some_value
end
```
This PR is to fix the issue by using `hint` to infer if the expected type of `false` literal is `false` (not `bool`).
=> Boolean literal may have type of `true` or `false`

lib/steep/subtyping/check.rb, test/subtyping_test.rb
Fix subtyping to let `1 <: 1 | 2 | 3` hold.
=> Fix literal type subtyping

lib/steep/subtyping/check.rb, lib/steep/type_construction.rb, test/subtyping_test.rb, test/type_construction_test.rb
This PR is to relax tuple typing which seems too restrictive because it doesn't allow the following:
```ruby
a = [1,2,3]
```
The hint for array literal should be expanded and then tested if it can be a tuple type.
=> Fix tuple typing

lib/steep/type_construction.rb, lib/steep/type_inference/logic.rb, test/logic_test.rb, test/type_construction_test.rb
It allows splats included in lhs.
```ruby
a, *b, c = [1,"2",1.2,:foo]          # ok!
```
=> Fix massign support

lib/steep/type_construction.rb, test/type_construction_test.rb
```ruby
foo.bar += 1       # Op_asgn node with lhs is `send`
```
=> Support send in op_send lhs

lib/steep/ast/types/union.rb, lib/steep/type_construction.rb, test/type_construction_test.rb
It skips adding argument types if method type is not given. This causes errors on _flow-sensitive_ analyses.
=> Fix arg typing without method type

lib/steep/type_construction.rb, test/type_construction_test.rb
Skip type checking for `alias` node.
=> Fix alias node handling

lib/steep/type_construction.rb, test/type_construction_test.rb
The result of `op_asgn` should be _non-null_.
=> Revise op_asgn lvar_env handling

lib/steep/ast/types.rb, lib/steep/ast/types/any.rb, lib/steep/ast/types/boolean.rb, lib/steep/ast/types/bot.rb, lib/steep/ast/types/class.rb, lib/steep/ast/types/factory.rb, lib/steep/ast/types/helper.rb, lib/steep/ast/types/instance.rb, lib/steep/ast/types/intersection.rb, lib/steep/ast/types/literal.rb, lib/steep/ast/types/name.rb, lib/steep/ast/types/nil.rb, lib/steep/ast/types/proc.rb, lib/steep/ast/types/record.rb, lib/steep/ast/types/self.rb, lib/steep/ast/types/top.rb, lib/steep/ast/types/tuple.rb, lib/steep/ast/types/union.rb, lib/steep/ast/types/var.rb, lib/steep/ast/types/void.rb, lib/steep/interface/method_type.rb, lib/steep/interface/substitution.rb, smoke/hash/d.rb
These changes make type checking run 40% faster. 🚀
=> Speed up type checker

lib/steep/subtyping/check.rb, test/subtyping_test.rb, test/test_helper.rb, test/type_construction_test.rb
To give `[1.0]` type of `[Numeric]`.
The tuple types have been _invariant_ because letting them be _covariant_ makes the type checking _unsound_.
```rb
numbers = [1, 2]
objects = numbers       # This assignment is allowed if tuple types are covariant.
objects[0] = "string"   # This is allowed.
numbers[0] + 1          # Type checker cannot detect the runtime error raised here.
```
I'm making the tuples to be covariant because `Array[T]` is covariant already, even though it is incorrect.
* Closes https://github.com/soutaro/steep/issues/192
=> Make tuple types covariant

lib/steep/server/base_worker.rb, lib/steep/server/master.rb
When I run `steep watch` by mistake, it took a long time to stop the steep process. This PR tries to make it shorter.
For example, if I run `steep watch` in a large project directory like [Mastodon](https://github.com/tootsuite/mastodon), it takes about **40 seconds** currently to stop the watching process with `Ctrl+C`:
```sh
$ time bundle exec steep --log-level=fatal watch app/models/
[deprecation warnings omitted]
👀 Watching directories, Ctrl-C to stop.
^CShutting down workers... # I typed Ctrl+C immediately after 👀 printed
real	0m40.593s
user	0m48.878s
sys	0m1.637s
```
It takes only **4 seconds** if this PR applied.
```sh
$ time bundle exec steep --log-level=error watch app/models/
[deprecation warnings omitted]
👀 Watching directories, Ctrl-C to stop.
^CShutting down workers...
real …
```
=> Earlier shutdown with interruption while `steep watch`

lib/steep/ast/builtin.rb, lib/steep/ast/types/factory.rb, lib/steep/ast/types/name.rb, lib/steep/project/completion_provider.rb, lib/steep/project/hover_content.rb, lib/steep/subtyping/check.rb, lib/steep/type_construction.rb, test/test_helper.rb, test/type_factory_test.rb
This PR deprecates the `Name::Class` type, unifying to `Name::Module` type.
The difference between the two types is the `constructor` attribute, however it is no longer used. So, there is no reason to have two identical types.
=> Bye Name::Class type

lib/steep/ast/types/factory.rb, lib/steep/ast/types/intersection.rb, lib/steep/ast/types/union.rb, lib/steep/interface/interface.rb, lib/steep/interface/method_type.rb, lib/steep/subtyping/check.rb, lib/steep/type_construction.rb, smoke/alias/a.rb, smoke/case/a.rb, smoke/if/a.rb, smoke/rescue/a.rb, test/block_params_test.rb, test/interface_test.rb, test/test_helper.rb, test/type_construction_test.rb, test/type_factory_test.rb
Improves typing of method calls with block on _union_ type receivers. This gives better types for:
```rb
a = [1, ""].sample    # a: Integer | String
a.yield_self do       # This cannot type blocks well because of the receiver is union type. 😢 
...
end
```
This PR is to introduce union and intersection of _method types_ and using them solves the problem above.
=> Better union typing

lib/steep/type_construction.rb, lib/steep/type_inference/block_params.rb, test/type_construction_test.rb
While I have a plan to support this, it's not supported for now.
```rb
foo.each {|(x, y), z| ... }   # Masgn in block parameters are not supported.
foo.each {|pair, z|           # You can rewrite like this.
x, y = pair
...
}
```
=> Add UnsupportedSyntax error on masgn in block params

lib/steep/ast/types/factory.rb, test/type_construction_test.rb
Attribute definition in `Module` caused an error.
```
Unexpected error in #type_send: undefined method `instance?' for #<RBS::AST::Members::AttrAccessor:0x00007f83c0543468>
```
This is a bug introduced in 0.29.0.
=> Attribute definition raises error

lib/steep/project/completion_provider.rb, lib/steep/project/hover_content.rb, lib/steep/server/interaction_worker.rb, lib/steep/source.rb, test/source_test.rb
Type checking of a `def` in Steep is independent of other `def`s. We can just stop type checking for other `def`s for faster response on hover or completions.
```rb
class Foo
def foo
1+"     # Assume user triggers completion/hover here. 🈁
end
def bar
2+3     # The type checking of this method is not used at all for the completion/hover above.
end
def baz
:xyz    # We can delete these defs. 🔪 
end
end
```
The test on my computer resulted in 4 times speedup of completion, from 2 seconds to 0.5 seconds. This is a huge performance improvement that 2 seconds is clearly too slow, but 0.5 seconds would be acceptable.
=> Run type checker for interactions without unrelated defs

steep.gemspec
It's already [fixed in Listen repo](https://github.com/guard/listen/commit/819604fe69ca416d1797ccacb5508395ad896175) but not released yet. Fixes #233.
=> Listen ~> 3.0 to allow installing on Ruby 3

lib/steep/source.rb, test/source_test.rb
`if` with `then` caused an error. 😢 
```rb
if foo() then bar() else baz() end    # => Unexpected error: #<NoMethodError: undefined method `loc' for #<Parser::Source::Range:0x00007f8987c09758>>
```
=> Support if-then-else

lib/steep/type_inference/logic_type_interpreter.rb, test/type_construction_test.rb
Let type-case infer the type of variable even if the variable has an interface type.
=> Let type-case work for interface types

lib/steep/ast/types/factory.rb, smoke/regression/fun.rb, smoke/regression/fun.rbs, test/type_construction_test.rb
=> Fix flow sensitive

lib/steep/type_construction.rb, test/type_construction_test.rb
Attribute assignments evaluate to the rhs values regardless the return value of the method.
```
foo.bar = :foo      # Always :foo
foo[1] = :bar       # Always :bar
```
So the type of these nodes should be the type of rhs nodes.
=> Attribute assignments have rhs type

lib/steep.rb, lib/steep/annotation_parser.rb, lib/steep/ast/types/factory.rb, lib/steep/errors.rb, lib/steep/interface/method_type.rb, lib/steep/method_name.rb, lib/steep/project/completion_provider.rb, lib/steep/project/source_file.rb, lib/steep/server/interaction_worker.rb, lib/steep/subtyping/variable_occurrence.rb, lib/steep/type_construction.rb, lib/steep/type_inference/context.rb, lib/steep/type_inference/local_variable_type_env.rb, lib/steep/type_inference/method_call.rb, lib/steep/typing.rb, test/annotation_parsing_test.rb, test/completion_provider_test.rb, test/test_helper.rb, test/type_construction_test.rb, test/type_factory_test.rb, test/typing_test.rb
Introduces an intermediate data structure `MethodCall` that records which methods are called. This is to calculate statistics data and implementing LSP features (jump to definition, ...).
=> Fix method call typing

lib/steep/type_construction.rb, test/type_construction_test.rb
Add types for constant parts.
```ruby
::A::B::C
^^^^^^^^^   -> Has type
^^^^^^      -> No type has been assigned! 🤯 
```
=> Type constant parts

lib/steep/drivers/print_project.rb
`steep project` prints the directories to load library RBSs from for troubleshooting.
Example:
```
$ bundle exec steep project
Target:
app:
sources:
patterns:
- lib
ignores:
files:
- lib/conference.rb
signatures:
patterns:
- sig
files:
- sig/conference.rbs
libraries:
- set
- pathname
library dirs:
- core: /Users/soutaro/src/steep/vendor/bundle/ruby/2.7.0/gems/rbs-0.16.0/core
- set: /Users/soutaro/src/steep/vendor/bundle/ruby/2.7.0/gems/rbs-0.16.0/stdlib/set/0
- pathname: /Users/soutaro/src/steep/vendor/bundle/ruby/2.7.0/gems/rbs-0.16.0/stdlib/pathname/0
```
=> Print environment paths in `project` command

lib/steep/subtyping/check.rb, lib/steep/type_construction.rb, test/subtyping_test.rb, test/test_helper.rb, test/type_construction_test.rb
* Support alias to record types (bug fix!)
* Record types are now co-variant
* Allows skipping `nil`-able attributes
```
x = { name: "foo", email: "foo@example.com" }          # OK
x = { name: "foo", email: nil }                        # OK
x = { name: "foo" }                                    # OK 🐕 
```
=> More flexible record typing

lib/steep/errors.rb, lib/steep/type_construction.rb, test/test_helper.rb, test/type_construction_test.rb
Fixes https://github.com/soutaro/steep/issues/261
=> Fix next error

lib/steep/errors.rb, test/errors_test.rb
This change aims to make error messages on the terminal easier to view with more colors.
Note that this keeps the message format the same still.
=> More colorful message

lib/steep/ast/types/factory.rb, lib/steep/ast/types/logic.rb, lib/steep/type_construction.rb, lib/steep/type_inference/logic_type_interpreter.rb, test/type_construction_test.rb
`condition:` keyword argument is true if the node is in the _conditional_ context.
=> Improve `&&` and `||` typing

lib/steep/ast/types/factory.rb, lib/steep/ast/types/logic.rb, lib/steep/type_construction.rb, lib/steep/type_inference/logic_type_interpreter.rb, smoke/type_case/a.rb, test/test_helper.rb, test/type_construction_test.rb
Steep now analyzes case-when exhaustiveness based on value equality with literal types.
```ruby
x = nil 
a = case x
when nil
true    # x: nil
when :foo
false   # x: :foo
when Symbol
true    # x: :bar
when Integer
false   # x: Integer
end       # And this case is exhaustive! ❗ 
```
=> Type-case based on literal value

lib/steep/type_construction.rb, test/type_construction_test.rb
Steep casts `untyped || something` to bool type, but I think it is not the expected behavior.
For example:
```ruby
a = _ = nil
b = a || 42
b[0]
```
```ruby
target :lib do
check 'test.rb'
end
```
```console
$ steep check
test.rb:6:0: NoMethodError: type=bool, method=[] (b[0])
```
In this case, I expect `b` is also `untyped` because it is introduced by `a` (== `untyped`). But actually it is `bool`. So I got the `NoMethodError` unexpectedly.
Stop casting `x || y` to `bool` type if the LHS (`x`) is `untyped`.
=> Do not cast `untyped || something` to bool type

lib/steep/type_construction.rb, test/type_construction_test.rb
=> Fix error on implicit `to_proc` syntax when `untyped` is yielded

lib/steep/diagnostic/signature.rb, smoke/diagnostics-rbs-duplicated/test_expectations.yml, smoke/diagnostics-rbs/test_expectations.yml
`code` should be `RBS::***`, not `Ruby::***`.
=> Fix Signature diagnostics #code

lib/steep/project/source_file.rb, lib/steep/type_construction.rb, test/project_file_test.rb, test/type_construction_test.rb
Report with `UnexpectedError` diagnostics, instead of ignoring them.
=> Fix RBS error handling

lib/steep/diagnostic/signature.rb, lib/steep/signature/validator.rb, lib/steep/subtyping/check.rb, test/validation_test.rb
RBS allows declaring _module-self-types_ which is a requirement for classes or modules to mix-in the module. This PR implements a validation if the requirement is satisfied.
This PR also adds type checking for types of instance variables.
=> Add validations for module-self-types and instance variables

lib/steep/index/signature_symbol_provider.rb, lib/steep/server/master.rb, lib/steep/server/type_check_worker.rb, lib/steep/services/signature_service.rb, test/lsp_double.rb, test/master_test.rb, test/signature_symbol_provider_test.rb, test/type_check_worker_test.rb
Implement `workspace/symbol` request handling based on the abstractions introduced in #312.
=> Let TypeCheckWorker handle workspace/symbol request

lib/steep/cli.rb, lib/steep/drivers/check.rb, lib/steep/drivers/langserver.rb, lib/steep/drivers/watch.rb, lib/steep/drivers/worker.rb, lib/steep/server/change_buffer.rb, lib/steep/server/interaction_worker.rb, lib/steep/server/type_check_worker.rb, lib/steep/server/worker_process.rb, test/master_test.rb, test/type_check_worker_test.rb
This allows specifying part of a project through command line arguments to type check.
```
$ steep check lib/steep/ast lib/steep/cli.rb
```
=> Pass commandline args to workers

lib/steep/server/type_check_worker.rb
Errors reported to Ruby code can be ignored.
=> Emit diagnostics with respect to target config

lib/steep.rb, lib/steep/cli.rb, lib/steep/drivers/check.rb, lib/steep/drivers/langserver.rb, lib/steep/drivers/utils/jobs_count.rb, lib/steep/drivers/watch.rb, steep.gemspec
The default is calculated from _# of cores_.
* Added `parallel` gem as dependency for `#physical_processor_count`.
=> Add -j option to control number of workers

lib/steep.rb, lib/steep/ast/types/class.rb, lib/steep/drivers/validate.rb, lib/steep/server/change_buffer.rb, lib/steep/server/master.rb, lib/steep/services/signature_service.rb, lib/steep/services/type_check_service.rb, lib/steep/signature/validator.rb, lib/steep/subtyping/check.rb, lib/steep/subtyping/constraints.rb, lib/steep/type_construction.rb, lib/steep/type_inference/local_variable_type_env.rb, lib/steep/type_inference/logic_type_interpreter.rb, lib/steep/type_inference/type_env.rb, test/constraints_test.rb, test/local_variable_type_env_test.rb, test/logic_test.rb, test/rbs_index_test.rb, test/subtyping_test.rb, test/test_helper.rb, test/type_construction_test.rb, test/type_env_test.rb
Performance improvement is accomplished by:
1. Faster `#charpos` ([\#617](https://github.com/ruby/rbs/pull/617))
2. `RBS::DefinitionBuilder` optimization ([\#619](https://github.com/ruby/rbs/pull/619), [\#620](https://github.com/ruby/rbs/pull/620))
3. Partial type name resolution ([\#621](https://github.com/ruby/rbs/pull/621))
=> Performance improvement

lib/steep/cli.rb, lib/steep/drivers/watch.rb, test/cli_test.rb
You can specify Ruby source code files.
```
$ steep watch sig app/models/user.rb       # This ignores changes on app/models/group.rb
```
=> Let watch command support watching files

lib/steep/diagnostic/ruby.rb, smoke/unexpected/Steepfile, smoke/unexpected/test_expectations.yml, smoke/unexpected/unexpected.rb, smoke/unexpected/unexpected.rbs
Stop printing all of the stack trace in the diagnostic.
=> Fix unexpected error handling

lib/steep/server/master.rb, test/lsp_double.rb, test/master_test.rb, test/test_helper.rb
1. Use `initialized` notification to start type checking
2. Confirm if `window/workDoneProgress/create` is supported
=> Small LSP improvements

lib/steep/diagnostic/ruby.rb, lib/steep/type_construction.rb, test/type_construction_test.rb
Passing `nil` as a block doesn't give a block.
```ruby
[1,2,3].each(&nil)        # Returns an Enumerator because block is not given!
```
Fixes https://github.com/soutaro/steep/issues/268.
=> Fix type checking passing `nil` as a block

lib/steep/type_construction.rb, smoke/regression/issue_332.rb, smoke/regression/issue_332.rbs, smoke/regression/test_expectations.yml, test/test_helper.rb, test/type_construction_test.rb
`super` calls with unresolved overloading result in `undefined method "add_call"`. This is to fix the `add_call` error.
The type checking still fails, because of `UnresolvedOverloading`.
Related to https://github.com/soutaro/steep/issues/332.
Fixes https://github.com/soutaro/steep/issues/345.
=> Fix unexpected `add_call` call

lib/steep.rb, lib/steep/cli.rb, lib/steep/drivers/stats.rb, steep.gemspec, test/cli_test.rb, test/test_helper.rb
`steep stats` now support _table_ and _csv_ printing modes. Users can specify the mode through `--format` options.
```shell
$ steep stats --format=table
Target  File                                         Status   Typed calls  Untyped calls  All calls  Typed %
--------------------------------------------------------------------------------------------------------------
test    argument_type_mismatch.rb                    success            0              0          1       0%
test    block_body_type_mismatch.rb                  success            1              0          2      50%
test    block_type_mismatch.rb                       success            0              2          3       0%
test    break_type_mismatch.rb                       success            1              0          1 …
```
=> Pretty table printing

lib/steep/server/master.rb, test/master_test.rb
This happens when
* Client sends `textDocument/didChange` notification for non-typechecked files => the changes is not recorded
* Client then sends `textDocument/didSave` notification for the file => `make_request` returns `nil`
* 💥
=> Skip #start_type_check if request is nil

lib/steep/server/interaction_worker.rb
Sublime LSP plugin doesn't send the `context` when doing a `textDocument/completion` request:
```
:: --> ruby textDocument/completion(7): {'position': {'line': 10, 'character': 21}, 'textDocument': {'uri': 'file://[redacted]/app.rb'}}
```
This causes Steep to crash with `NoMethodError (undefined method '[]' for nil:NilClass)`.
I'm not sure if this is a violation of the protocol, but it looks like `trigger` isn't used for anything important in Steep, so let's handle it gracefully.
=> Do not crash when completion request context is missing

lib/steep/services/goto_service.rb, test/goto_service_test.rb
It's useful to resolve `.new` to `#initialize` method.
Related to https://github.com/soutaro/steep/issues/368.
=> Handling goto-definition of `.new` method

lib/steep/server/master.rb
Goto declaration and goto type-definition are not implemented.
=> Fix initialize return value

lib/steep/services/goto_service.rb, test/goto_service_test.rb
_Calls_ for `send` nodes with blocks are recorded with the `block` nodes.
=> Fix goto definition/implementation from block

lib/steep/services/file_loader.rb, test/cli_test.rb, test/file_loader_test.rb
The previous behavior resulted in a crash when a non-project file is given to `steep check`.
```
$ steep check README.md # => Unexpected error: #<NoMethodError: undefined method `name' for nil:NilClass>
```
=> Fix FileLoader to skip files not matching to the given pattern

lib/steep/server/interaction_worker.rb, lib/steep/services/hover_content.rb, test/hover_test.rb, test/interaction_worker_test.rb
we now display type information when alias is hovered in rbs 
The judgment when hovering is off by one character.
I think this is a location issue, so I'll fix it in a later PR.
=> Display type information when type alias is hovered in rbs

lib/steep/diagnostic/ruby.rb, lib/steep/type_construction.rb, test/type_construction_test.rb
Breaking without value often happens and causes type errors.
```rb
[1,2,3].each do |i|
break      # Type error because the #each method expects Array[Integer]
end
```
This cannot be handled well under the current type checker architecture, so assigning another error code would help to ignore this type errors if the user wants it.
=> Assign different error code to break without value

lib/steep/type_construction.rb, test/type_construction_test.rb
This is a special case for `break` from `#loop`.
```
loop do
break if foo
end
```
1. The return type of `#loop` is `bot`, which implies the return value is not used
2. It `break`s without value == returning no value
3. Hiding type error for that `break` would make sense 💡
=> Allow break without value from bot methods

lib/steep/server/interaction_worker.rb, lib/steep/services/hover_content.rb, test/hover_test.rb, test/interaction_worker_test.rb
add hover supports for `RBS::Types::ClassInstance`, `RBS::Types::ClassSingleton` and `RBS::Types::Interface`.
When these are hovered, the information and comments will now be displayed!
crate a rbs file with this content and you can confirm that you can see the information when you hover them
```rbs
class Foo [T] < Parent[T]
end
class Parent [in T]
end
module Hoge
end
class Qux
@foo: Foo[Hoge]
end
interface _Fooable
def foo: () -> nil
end
class C
def foo: (_Fooable) -> singleton(String)
end
```
=> Extend the functionality of hover in rbs files.

lib/steep/diagnostic/ruby.rb, smoke/class/test_expectations.yml, smoke/diagnostics/test_expectations.yml, smoke/ensure/test_expectations.yml, smoke/method/test_expectations.yml, smoke/rescue/test_expectations.yml, smoke/toplevel/test_expectations.yml
This PR is to report method body type error only for method name, because reporting type error for all of `def` syntax looks really verbose and hides other errors inside the method definition.
=> Compact error reporting for method body type mismatch

lib/steep/diagnostic/signature.rb, smoke/diagnostics-rbs/mixin-class-error.rbs, smoke/diagnostics-rbs/test_expectations.yml
If `RBS::MixinClassError` is raised during a steep check, the steep worker thread will be in a wait state forever.
With this fix, not only will steep not stop when `RBS::MixinClassError` is raised, but it will also show the problem.
```
mixin-class-error.rbs:5:2: [error] Cannot include a class `::Foo` in the definition of `::Bar`
│ Diagnostic ID: RBS::MixinClassError
│
└   include Foo
~~~~~~~~~~~
```
=> Fix Unexpected error

lib/steep/project/dsl.rb, lib/steep/project/options.rb, lib/steep/project/target.rb, test/steepfile_test.rb, test/target_test.rb
The `vendor` DSL was broken. This PR introduces new `stdlib_path` DSL to customize _core_root_ and _stdlib_root_ with keyword argument.
```rb
target(:app) do
stdlib_path(
core_root: "vendor/rbs/core",              # Load core RBS from vendor/rbs/core/*.rbs
stdlib_root: nil                           # Load stdlib RBS from default place
)
end
target(:test) do
stdlib_path(
core_root: false,        # Skip loading core RBSs
stdlib_root: false       # Skip loading stdlib RBSs
)
signature "sig"            # You have to write RBS files of core classes in "sig" directory
end
```
=> Revise path DSL

lib/steep/project/dsl.rb, test/steepfile_test.rb
This helps users to update their configuration:
```
[Steep 0.45.0] [Steepfile] [target=app] #typing_options is deprecated and has no effect as of version 0.46.0. Update your Steepfile as follows for (almost) equivalent setting:
[Steep 0.45.0] [Steepfile] [target=app]   # D = Steep::Diagnostic                          # Define a constant to shorten namespace
[Steep 0.45.0] [Steepfile] [target=app]   configure_code_diagnostics(D::Ruby.strict)       # :strict
[Steep 0.45.0] [Steepfile] [target=app]   configure_code_diagnostics do |hash|
[Steep 0.45.0] [Steepfile] [target=app]     hash[D::Ruby::MethodDefinitionMissing] = nil   # allow_missing_definitions
[Steep 0.45.0] [Steepfile] [target=app]     hash[D::Ruby::FallbackAny] = nil               # allow_fallback_any
[Steep 0.45.0] [Steepfile] …
```
=> Print instruction to update configuration

lib/steep/services/hover_content.rb, test/hover_test.rb
Fixed an error that occurred when hovering the IDE cursor over a comment in rbs file.
=> Fix error when hover on comment for rbs

Gemfile.lock, lib/steep/project/dsl.rb, lib/steep/project/options.rb, lib/steep/project/target.rb, steep.gemspec, test/steepfile_test.rb
This PR introduces `rbs collection` feature, https://github.com/ruby/rbs/pull/589,  to Steep.
* If `rbs_collection.yaml` exists in the same directory as `Steepfile`, Steep loads libraries' RBSs from the config file.
* If `collection_config path` is specified in Steepfile, Steep loads libraries' RBSs from the specified file.
* I suppose the configuration will be used like `collection_config '../other/path/rbs_collection.yaml'` in many cases.
* If `disable_collection` is specified in Steepfile, Steep ignores `rbs_collection.yaml`.
* If `rbs_collection.yaml` doesn't exist and no options are specified, Steep does nothing about rbs collection feature.
=> Enable RBS collection feature

lib/steep.rb
Fixed a issue where the percentile display would be `0` if there were few samples.
```
$ ruby -r steep -e 'Steep.measure2("test", level: :error) { |s| 3.times { |i| s.sample(i) { sleep(i / 10.0) } } }'
[Steep 0.46.0] 0.308099secs for "test"
[Steep 0.46.0]   Average: 0.10269966666666668secs
[Steep 0.46.0]   Median: 0.205162secs
[Steep 0.46.0]   Samples: 3
[Steep 0.46.0]   99 percentile: 0secs
[Steep 0.46.0]   90 percentile: 0secs
[Steep 0.46.0]   10 Slowests:
[Steep 0.46.0]     2 (0.205162secs)
[Steep 0.46.0]     1 (0.10291secs)
[Steep 0.46.0]     0 (2.7e-05secs)
```
```
$ ruby -r steep -e 'Steep.measure2("test", level: :error) { |s| 3.times { |i| s.sample(i) { sleep(i / 10.0) } } }'
[Steep 0.46.0] 0.305917secs for "test"
[Steep 0.46.0]   Average: 0.10197233333333333secs
[Steep 0.46.0] …
```
=> Fix percentile

lib/steep/type_inference/block_params.rb, test/block_params_test.rb
Steep will raise UnexpectedError when non-annotated block params with rest variable.
```rb
a = ->(*res) { }
```
=> Fix NoMethodError on block params with rest var

lib/steep/server/interaction_worker.rb
There are two problems with the current completion function.
- If I want to complete a method such as `default_value`, `def` part will be completed.
- Type parameters are also being completed.
https://user-images.githubusercontent.com/935310/135632516-706616e6-c46a-420e-b804-008274931427.mov
So, the following fixes have been made.
- Remove the `def ` part from the completion target.
- Remove type parameters from the completion target as well. Instead, put type parameters in `detail`.
This solves the problem, but the downside is that the type parameter that used to show up in all completion lists is now only the one you have selected.
https://user-images.githubusercontent.com/935310/135633224-634bcbf4-f61f-4502-bb24-4607656aea62.mov
=> Adjusting display of CompletionItem

lib/steep/type_construction.rb, test/type_construction_test.rb
https://github.com/ruby/gem_rbs_collection/pull/68 seems raise Unexpected error.
I've investigated and fixed it, because it seems that `Steep::TypeConstruction#type_hash_record` didn't consider the case of kwargs enough.
=> Fix Unexpected error if record-type receive kwargs

README.md
The Phone class should have `attr_reader  :country, :number` if Phone#== uses `other.country` and `other.number`.
=> Add a missing attr_reader in the example code

lib/steep/type_inference/send_args.rb
The following code raises an unexpected error.
```rb
[].each(*a)
```
```
Unexpected error: #<NoMethodError: undefined method `each' for nil:NilClass>
/Users/ksss/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/steep-0.46.0/lib/steep/type_inference/send_args.rb:156:in `uniform_type'
/Users/ksss/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/steep-0.46.0/lib/steep/type_inference/send_args.rb:567:in `block in each'
...
```
=> Should check if positional_params is nil or not

Gemfile.lock, steep.gemspec
It is intended to require only `1.7.x` with release version of Steep because the new features introduced in RBS 1.8 is not supported yet.
This is only for the `HEAD` version for a while. I will update the code to support the new features, but I don't have time for it now. 👶
=> Relax RBS gemspec requirements

lib/steep.rb
`active_support` must be explictly required according to: https://guides.rubyonrails.org/active_support_core_extensions.html
The requirement of `active_support/tagged_logging` is removed because `active_support` autoloads it.
Closes #466 and #473.
=> Fix ActiveSupport requirement in lib/steep.rb

Gemfile.lock, steep.gemspec
Reverts soutaro/steep#460
This is to release 0.47.1. I'm still working for RBS 2.0 support. 💪
=> Revert "Relax RBS gemspec requirements"

lib/steep.rb, lib/steep/ast/types/factory.rb, lib/steep/ast/types/var.rb, lib/steep/diagnostic/signature.rb, lib/steep/interface/method_type.rb, lib/steep/interface/type_param.rb, lib/steep/services/type_check_service.rb, lib/steep/signature/validator.rb, lib/steep/subtyping/cache.rb, lib/steep/subtyping/check.rb, lib/steep/subtyping/constraints.rb, lib/steep/subtyping/result.rb, lib/steep/type_construction.rb, lib/steep/type_inference/context.rb, sample/lib/length.rb, sample/sig/length.rbs, test/constraints_test.rb, test/interface_test.rb, test/subtyping_test.rb, test/test_helper.rb, test/type_construction_test.rb, test/type_factory_test.rb, test/typing_test.rb, test/validation_test.rb
Finally the new features of RBS 2 are supported! 🎉 
Closes https://github.com/soutaro/steep/issues/487
=> Bounded generics

lib/steep/ast/types/factory.rb, test/type_construction_test.rb
Narrowing `bool` type to `false` (or `true`) causes problem when updating flags inside loops.
```rb
flag = true
while flag
if something
flag = false       # Reporting error here doesn't make any sense.
end
end 
```
=> Disable contextual typing with bool

lib/steep/ast/types/any.rb, lib/steep/ast/types/boolean.rb, lib/steep/ast/types/bot.rb, lib/steep/ast/types/class.rb, lib/steep/ast/types/helper.rb, lib/steep/ast/types/instance.rb, lib/steep/ast/types/intersection.rb, lib/steep/ast/types/literal.rb, lib/steep/ast/types/logic.rb, lib/steep/ast/types/name.rb, lib/steep/ast/types/nil.rb, lib/steep/ast/types/proc.rb, lib/steep/ast/types/record.rb, lib/steep/ast/types/self.rb, lib/steep/ast/types/top.rb, lib/steep/ast/types/tuple.rb, lib/steep/ast/types/union.rb, lib/steep/ast/types/var.rb, lib/steep/ast/types/void.rb, lib/steep/interface/function.rb, lib/steep/subtyping/check.rb, test/type_construction_test.rb
`Enumerable#flat_map` haven't type checked as expected in Steep.
```
[1,2,3].flat_map {|x| [x.to_s] }          # Steep infers Array[Array[String]] while we need Array[String] here
```
This is because the subtyping relationship `Array[String] <: (A | Array[A])` resolves to a substitution of `A == Array[String]`. If it resolves to a substitution of `A == String`, the type checking will work.
So, we'd like to introduce a function `#hole_path`. It takes two arguments, type and type variables, and returns the shortest path to _unknown_ variable. Giving higher precedence to types with longer path will result more specific (smaller) type variable assignment.
This depends on two intuitions (without any proof):
1. Specific type is better (`A == String` is better than `A == Array[String]`)
2. …
=> Fix for `#flat_map`

lib/steep/diagnostic/ruby.rb, lib/steep/type_construction.rb, smoke/diagnostics/proc_type_expected.rb, smoke/diagnostics/test_expectations.yml, test/type_construction_test.rb
* An error was raised when giving non-proc type hint
* Report a issue when non-proc type annotation is given to block parameter
=> Fix lambda typing

lib/steep/signature/validator.rb, test/validation_test.rb
```
type x[A < Numeric] = A
class Foo[X0 < String]
def f: () -> Array[x[X0]]       # Steep didn't detect error here, because `x` is inside `Array`.
end
```
=> Validate type decendants

lib/steep/drivers/check.rb
Steep command is could execute for sub project:
```
$ bundle exec -- steep check --steepfile=sample/Steepfile
..................................................................
No type error detected. 🫖
```
But, raise exception when type check is failed:
```
$ bundle exec -- steep check --steepfile=sample/Steepfile
...............................................FF.................
#<Errno::ENOENT: No such file or directory @ rb_sysopen - lib/conference.rb>
/path/to/steep/lib/steep/drivers/check.rb:218:in `read'
/path/to/steep/lib/steep/drivers/check.rb:218:in `read'
/path/to/steep/lib/steep/drivers/check.rb:218:in `block in print_result'
/path/to/steep/lib/steep/drivers/check.rb:216:in `each'
/path/to/steep/lib/steep/drivers/check.rb:216:in `print_result' …
```
=> Fix print error with absolute path

lib/steep/services/type_check_service.rb
Errors were reported when `steep stats` receives non-project Ruby file.
```
[Steep 0.49.0] [typecheck:typecheck@5] [background] Unexpected error: #<NoMethodError: undefined method `name' for nil:NilClass
signature_service = signature_services[target.name]
^^^^^>
[Steep 0.49.0] [typecheck:typecheck@5] [background]   /Users/soutaro/src/steep/lib/steep/services/type_check_service.rb:274:in `block (2 levels) in typecheck_source'
[Steep 0.49.0] [typecheck:typecheck@5] [background]   /Users/soutaro/src/steep/lib/steep.rb:166:in `measure'
[Steep 0.49.0] [typecheck:typecheck@5] [background]   /Users/soutaro/src/steep/lib/steep/services/type_check_service.rb:273:in `block in typecheck_source'
[Steep 0.49.0] [typecheck:typecheck@5] [background] …
```
=> Skip non-target ruby code on `steep stats`

lib/steep/server/interaction_worker.rb, lib/steep/server/master.rb, lib/steep/server/type_check_worker.rb, lib/steep/server/worker_process.rb, lib/steep/services/goto_service.rb, test/goto_service_test.rb, test/interaction_worker_test.rb
Found minor problems when I was testing with Sublime LSP.
* Pass `--log-output` command line argument to workers so that we can use `tail -f` for LSP logs
* Delete percentage `(55%)` message from LSP progress since Sublime LSP prints the percentage itself (Why VSCode doesn't print it...)
* Strip HTML comment from markdown message since Sublime LSP doesn't handle them
* Filter *Goto definition* results from workers (VSCode automatically de-dup the list, but Sublime LSP doesn't)
* Fix RBS type name completion insertion duplication
=> LSP related improvements for Sublime LSP

lib/steep/cli.rb, lib/steep/drivers/check.rb, lib/steep/drivers/langserver.rb, lib/steep/drivers/stats.rb, lib/steep/drivers/utils/jobs_count.rb, lib/steep/drivers/watch.rb, lib/steep/server/worker_process.rb, test/cli_test.rb
I think to execute Steep with [Bazel](https://bazel.build/) and [rules_ruby](https://github.com/bazelruby/rules_ruby).
So, I writen Bazel configuration as follows.
```starlark
ruby_test(
name = "typecheck",
main = "@bundle_example//:bin/steep",
args = [
"check",
"--steepfile=example/Steepfile",
],
srcs = ["Steepfile", ":lib"] + glob(["sig/**/*.rbs"]),
deps = [":lib", "@bundle_example//:bin"],
)
```
But, `bazel test` is failed.
```
#<Errno::ENOENT: No such file or directory - steep>
/.rbenv/versions/3.1.1/lib/ruby/3.1.0/open3.rb:222:in `spawn'
/.rbenv/versions/3.1.1/lib/ruby/3.1.0/open3.rb:222:in `popen_run'
/.rbenv/versions/3.1.1/lib/ruby/3.1.0/open3.rb:161:in `popen2'
/execroot/rules_steep/bazel-out/darwin-fastbuild/bin/example/typecheck-test.runfiles/bundle_example/lib/ruby/3.1.0/bundler …
```
=> CLI option for override steep command at spawn worker

Gemfile, lib/steep/project.rb, lib/steep/server/master.rb, lib/steep/server/type_check_worker.rb, lib/steep/server/worker_process.rb
This PR adds support for Windows.
Sometimes drive letter (`e:`) is missing (maybe language_server-protocol bug?), so it may error if the work that is on multiple drives.
This closes #383.
=> Add: Support Windows environment

lib/steep/interface/function.rb, lib/steep/type_construction.rb, test/type_construction_test.rb
* Check if there is _required_ (== non-optional) parameters
* Pick the first method return type rather than union
=> Let `&:foo` proc work with methods with optional parameters

lib/steep/type_construction.rb, test/type_construction_test.rb
Fix https://github.com/soutaro/steep/issues/515
or-asgn/and-asgn may differ in the number of children under the send node.
```
$ ruby-parse --legacy -e 'a=[]; a[0] ||= 3'
(begin
(lvasgn :a
(array))
(or-asgn
(send
(lvar :a) :[]
(int 0)) # <= `(int 0)` is asgn.children[2]
(int 3)))
$ ruby-parse --legacy -e 'self.a ||= 3'
(or-asgn
(send
(self) :a) # <= not have asgn.children[2]
(int 3))
```
This PR support both pattern.
=> Fix unexpected error when or-asgn/and-asgn

lib/steep/services/goto_service.rb, test/goto_service_test.rb
```rb
array.each do |x|
x.foo()       # Goto from the `foo` didn't work
end
```
=> Fix goto-definition from method call inside block

lib/steep/type_construction.rb, test/type_construction_test.rb
Closes https://github.com/soutaro/steep/issues/498
=> Better splat in array typing

lib/steep/cli.rb
This PR adds banner for showing available commands when using `--help` option.
```bash
$> steep --help                                                                                                                                                                         
Usage: steep [options]
--version
--log-level=LEVEL            Specify log level: debug, info, warn, error, fatal
--log-output=PATH            Print logs to given path
--verbose                    Set log level to debug
```
```bash
$> steep --help                                                                                                                                                        
Usage: steep [options]
available commands: init, check, validate, annotations, version, project, watch, langserver, stats …
```
=> Show available commands when using --help

lib/steep/source.rb, test/hover_test.rb
Since heredoc contents are placed outside of the node, we need a special handling to support hover and completion in heredoc.
=> Let hover/completion work in heredoc

lib/steep/type_construction.rb, smoke/diagnostics/test_expectations.yml, test/type_construction_test.rb
Found and fixed two bugs.
1. The `:const` node didn't have type if it's unknown
2. Reporting all of the constant components look too noisey (see below)
Before:
```
lib/rbs_protobuf/translator/base.rb:17:22: [information] Cannot find the declaration of constant: `Google`
│ Diagnostic ID: Ruby::UnknownConstant
│
└         @response ||= Google::Protobuf::Compiler::CodeGeneratorResponse.new
~~~~~~
lib/rbs_protobuf/translator/base.rb:17:30: [information] Cannot find the declaration of constant: `Protobuf`
│ Diagnostic ID: Ruby::UnknownConstant
│
└         @response ||= Google::Protobuf::Compiler::CodeGeneratorResponse.new
~~~~~~~~
lib/rbs_protobuf/translator/base.rb:17:40: [information] Cannot find the declaration of constant: `Compiler`
│ Diagnostic ID: Ruby::UnknownConstant
│
└ …
```
=> Better constant typing

lib/steep/subtyping/check.rb, test/type_construction_test.rb
Subtyping between union types can be improved by skipping common types. This happens on `#flat_map`.
Assume the following type definition:
```rbs
class Array[Element]
def flat_map: [T] () { (Element) -> (T | nil | false) } -> Array[T]
end
```
and a Ruby code
```rb
[1, 2, 3].flat_map do |i|
if i.odd?
i.to_s
end
end
```
We want the type of the expression to be `Array[String]`, but it returns `Array[String | nil]`. A subtyping check happens with `String | nil <: T | nil | false`, and was solved to `T == String | nil`.
The hack is to try types without type variables before types with type variables.
1. `nil <: T | nil | false` tries `nil <: nil` and `nil <: false` before `nil <: T`.
2. The `nil <: nil` holds, and the later `nil <: T` isn't tried.
And we have `Array[String]`! 🎉
=> Better union-union subtyping

lib/steep/server/lsp_formatter.rb, lib/steep/type_construction.rb, test/ruby_hover_test.rb, test/server/lsp_formatter_test.rb, test/type_construction_test.rb
* Let `MethodCall#return_type` have optional type
* Print the optional type in LSP hover
=> Better send support in MethodCall

lib/steep/ast/types/factory.rb, test/type_construction_test.rb
This allows the following code to type check.
```rb
doc = foo()                             # doc: String?
doc = bar() unless !doc || doc.empty?   # !doc may call NilClass#! which prevents flow-sensitive typing working
```
This PR makes `NilClass#!` special method.
=> Make `NilClass#!` a special method

lib/steep/cli.rb, test/cli_test.rb
- Use `ROOT_DIR` instead of `Gemfile` dir, assuming the repository root
- Add CLI option to specify `ROOT_DIR`
=> Fix binstub

lib/steep/type_construction.rb, test/type_construction_test.rb
The error message is printed because `Factory#interface` is called with unsupported types. This commit adds a guard.
Fixes #542
=> Remove `to_a` error message

lib/steep/type_inference/method_params.rb, test/type_construction_test.rb
With rest and keyword params.
Type checking the following type definition fails.
```rbs
class Foo
def bar: (*String, name: String) -> void
end
```
```rb
class Foo
def bar(*args, name:)      # <- type error reported here
end
end
```
=> Fix method parameter type checking

lib/steep/type_construction.rb, test/type_construction_test.rb
```rb
a, b, c = _ = nil         # Defines local variables on lhs even if rhs is `untyped`
a, * = foo()              # Splat assignment may be unnamed
```
=> Better masgn

lib/steep/type_construction.rb, test/test_helper.rb, test/type_construction_test.rb
#555 added support for `Array#compact`. This branch adds similar support for `Hash#compact`.
=> Add support for `Hash#compact`

test/index_test.rb
SourceIndexTest have 2 definitions in different files.
=> Fix conflict test class name

lib/steep/type_inference/logic_type_interpreter.rb, test/type_construction_test.rb
The `LogicTypeInterpreter` code assumes the `value_node` is `send` but doesn't confirm that. It resulted `Unknown node for type:` error.
=> Apply logic-type evaluation only if the node is `:send`

lib/steep/diagnostic/ruby.rb, lib/steep/type_construction.rb, test/type_construction_test.rb
Currently empty arguments passing to super makes UnexpectedError as below. So I needed to avoid the syntax as https://github.com/kachick/ruby-ulid/pull/189#discussion_r886930433
```
UnexpectedError: undefined method `selector' for #<Parser::Source::Map::Keyword:0x00007f53d402d878 @keyword=#<Parser::Source::Range lib/ulid/monotonic_generator.rb 269...274>, @end=#<Parser::Source::Range lib/ulid/monotonic_generator.rb 275...276>, @begin=#<Parser::Source::Range lib/ulid/monotonic_generator.rb 274...275>, @expression=#<Parser::Source::Range lib/ulid/monotonic_generator.rb 269...276>, @node=s(:super)>
super(node: node, location: node.loc.selector)
^^^^^^^^^(Ruby::UnexpectedError)
```
When digging "super and zsuper with block", I found #512. So this PR tries to care the issue too.
Fixes #512
=> Fix super and zsuper with block

test/type_check_worker_test.rb, test/type_construction_test.rb
=> Fix discarded tests

lib/steep/ast/types/factory.rb, lib/steep/type_construction.rb, smoke/regression/lambda.rb, smoke/regression/test_expectations.yml, test/type_construction_test.rb
Fixes https://github.com/soutaro/steep/issues/551
=> Use given const_env when making a new `ModuleContext`

lib/steep/services/type_check_service.rb, test/type_check_service_test.rb
It reports no error on Ruby code, but RBS error message will help the developer to understand what is happening.
Fixes https://github.com/soutaro/steep/issues/547
=> Graceful (??) error handling with undefined outer module

lib/steep/type_construction.rb, test/type_construction_test.rb
Closes https://github.com/soutaro/steep/issues/533
=> Type check anonymous block forwarding

lib/steep/type_construction.rb, lib/steep/type_inference/type_env.rb, test/type_construction_test.rb
Fixes https://github.com/soutaro/steep/issues/549
=> Set up gvar env in methods

lib/steep/type_construction.rb, test/type_construction_test.rb
Currently assigning untyped singleton class making UnexpectedError and UnsupportedSyntax.
```
UnexpectedError: undefined method `constr' for nil:NilClass
constr = rhs_result.constr.update_lvar_env do |lvar_env|
^^^^^^^(Ruby::UnexpectedError)
sclass receiver must be instance type or singleton type, but type given `untyped`(Ruby::UnsupportedSyntax)
```
I personally want correct signature from the assigning sclass, however it looks intentionally ommited in https://github.com/soutaro/steep/pull/211.
So this PR just suppress the UnexpectedError and keep UnsupportedSyntax.
=> Avoid UnexpectedError when assigning untyped singleton class

lib/steep/drivers/watch.rb
Initially I wasn't sure if `🔬 Type checking updated files...` was a process that was taking a while to complete or not (it's not :)) but I've made a change to make it clear that the type-check is complete, which most of the time is almost instant.
=> Appends "done!" to the watch output when the type check is complete

lib/steep/type_construction.rb, lib/steep/type_inference/logic_type_interpreter.rb, lib/steep/type_inference/type_env.rb, sig/steep/ast/types/logic.rbs, sig/steep/ast/types/tuple.rbs, sig/steep/type_construction.rbs, sig/steep/type_inference/logic_type_interpreter.rbs, test/logic_type_interpreter_test.rb
Write it in a simple recursion:
* Straightforward implementation :+1:
* Precise variable assignment :+1:
* More meta data: returns a set of _refined objects_ too :+1:
* More `TypeEnv` instance allocations :-1:
Related to https://github.com/soutaro/steep/issues/590
=> Fix LogicTypeInterpreter implementation

lib/steep/subtyping/constraints.rb, lib/steep/type_construction.rb, sig/steep/ast/types/proc.rbs, sig/steep/subtyping/constraints.rbs, sig/steep/type_construction.rbs, test/type_construction_test.rb
Fixes https://github.com/soutaro/steep/issues/595
=> Fix type inference problem on generics

lib/steep/type_construction.rb, test/type_construction_test.rb
Currently super with block called on no super definition makes following errors
```ruby
super do
end #=> UnexpectedBlockGiven
super() do
end #=> UnexpectedBlockGiven
super(42) do
end #=> UnexpectedError: undefined method `selector' ...
```
So I want suppress them in this PR. 🙏
=> Fix super with block makes UnexpectedError when no super definition

lib/steep/diagnostic/signature.rb, lib/steep/signature/validator.rb, test/validation_test.rb
=> Revert "Revert "Add class variable validation""

lib/steep/subtyping/constraints.rb, lib/steep/type_construction.rb, lib/steep/type_inference/context.rb, sig/steep/diagnostic/ruby.rbs, sig/steep/interface/block.rbs, sig/steep/interface/function.rbs, sig/steep/interface/method_type.rbs, sig/steep/subtyping/constraints.rbs, sig/steep/type_construction.rbs, sig/steep/type_inference/context.rbs, smoke/diagnostics/test_expectations.yml, test/type_construction_test.rb
Closes #610 
Fix various random bugs uncovered with #610.
```rbs
class Foo
def ng: [T] (T) { () -> ^(T) -> T } -> T
end
```
```rb
Foo.new.ng(42) {-> int { int.to_int } }.to_int
```
* The original problem was `UnexpectedError` that is caused by accessing unknown type variable. This is fixed by updating `TypeVariableContext` on generic method call type inference. (ac3909023fa19ecf2e6f5d2801e2f6d7c367f740)
* Writing the type of some **Context classes uncovered `BreakContext` problems. (844b5aed4f003d067f873323069a2f8dbfe178db)
* _But, how about adding upper bound on generics type parameter?_ Resulted another bug of ignoring collected constraints during type inference by upper bound of generics type parameter. (af9ff2cb1044641e4229c10dd52548d30bd9e629)
* Adding generic upper bound for this …
=> Fix Issue 610

lib/steep/type_construction.rb, lib/steep/type_inference/logic_type_interpreter.rb, lib/steep/type_inference/multiple_assignment.rb, lib/steep/type_inference/type_env.rb, sig/steep/type_construction.rbs, sig/steep/type_inference/type_env.rbs, test/type_construction_test.rb
Special local variables — `_`, `__skip__`, and `__any` — always have `untyped` type.
=> Fix special local variable handling

lib/steep/type_construction.rb, sig/steep/node_helper.rbs, sig/steep/type_construction.rbs, test/type_construction_test.rb
Type narrowing on assignment is not working. 🤕 
```rb
if x = array.sample
x + 1     # Type error is reported unless `#sample` is _pure_ method call
end
```
=> Fix type narrowing on assignment

lib/steep/type_construction.rb, sig/steep/type_construction.rbs, test/type_construction_test.rb
The motivating example is the following:
```ruby
positionals, keywords = 
if keyword_hash?(array_content.last)
[array_content.take(array_content.size - 1), array_content.last || raise]
else
[array_content, nil]
end
```
The _then_ branch has type of `[Array[node], node]`, the _else_ branch has type of `[Array[node, nil]`, and the `if` node has type of of `[Array[node], node] | [Array[node], nil]`. However, we want `positional` to have type of `Array[node]` and `keywords` to have type of `node?`.
We add a transformation on multiple assignment:
1. If the type of right hand side is a union of tuple types `[A, B] | [C, D]`,
2. The right hand side will be translated to a tuple of union types `[A | B, C | D]`
We can justify the transformation because `[A | B, C | D]` is a super type `[A, B] | …
=> Make more multiple assignments type check

lib/steep/type_construction.rb, lib/steep/type_inference/block_params.rb, sig/steep/type_inference/block_params.rbs, smoke/regression/block_param_split.rb, smoke/regression/block_param_split.rbs, test/block_params_test.rb, test/type_construction_test.rb
Steep supports block parameter auto-splat on tuples and arrays.
```rb
array = ...
array.each do |x, y|
x + 1      # x is Integer
y + ""     # y is String
end
```
This PR is to let the array element a type alias -- like `Array[pair]` where `type pair = [Integer, String]`.
Note that this doesn't support `#to_ary` conversion, or the case the argument is a subclass of `Array`.
=> Unfold type alias before splatting on block parameters

Steepfile, lib/steep/drivers/check.rb, lib/steep/drivers/checkfile.rb, lib/steep/drivers/langserver.rb, lib/steep/drivers/stats.rb, lib/steep/drivers/watch.rb, lib/steep/drivers/worker.rb, lib/steep/server/master.rb, lib/steep/server/worker_process.rb, rbs_collection.steep.lock.yaml, rbs_collection.steep.yaml, sig/steep/drivers/worker.rbs, sig/steep/server/worker_process.rbs, test/master_test.rb
Use `#fork` to start worker processes if available. This makes starting new processes faster than using `#spawn`, and let `steep check` finish much faster when the computer has more cores (>~10).
=> Fork to start worker processes

sig/steep/ast/types/factory.rbs, sig/steep/diagnostic/ruby.rbs
While running `steep check` on my app, I got some errors raised from inside Steep gem. I soon learned from the documentation that I could mute these errors by adding `ignore` entry in my rbs_collection.yaml, but anyway it'd be better for steep not to raise when being type checked, so here are my quick fixes for two of them.
I'm sorry though, I couldn't fix all the errors. I'm still seeing the following error, but I'll leave it untouched because I'm not sure what is the proper fix.
```
.../steep/sig/steep/subtyping/check.rbs:100:44: [error] Type application of `::Steep::Subtyping::Relation` doesn't satisfy the constraints: (::Steep::Interface::Block | nil) <: ::Object
│ Diagnostic ID: RBS::UnsatisfiableTypeApplication
│
└       def expand_block_given: (Symbol name, …
```
=> Fixes for some RBS errors within steep gem

lib/steep/ast/types/helper.rb, lib/steep/ast/types/logic.rb, sig/steep/ast/types/any.rbs, sig/steep/ast/types/boolean.rbs, sig/steep/ast/types/bot.rbs, sig/steep/ast/types/class.rbs, sig/steep/ast/types/helper.rbs, sig/steep/ast/types/instance.rbs, sig/steep/ast/types/intersection.rbs, sig/steep/ast/types/logic.rbs, sig/steep/ast/types/name.rbs, sig/steep/ast/types/nil.rbs, sig/steep/ast/types/record.rbs, sig/steep/ast/types/self.rbs, sig/steep/ast/types/top.rbs, sig/steep/ast/types/tuple.rbs, sig/steep/ast/types/union.rbs, sig/steep/ast/types/var.rbs, sig/steep/ast/types/void.rbs
```
Unexpected error: #<NoMethodError: undefined method `level' for #<Steep::AST::Types::Logic::Not:0x00000002801976c0>>
```
=> Add missing `#level` method

lib/steep/diagnostic/ruby.rb, lib/steep/type_construction.rb, test/type_construction_test.rb
`FalseAssertion` is unexpectedly reported:
```ruby
path = nil #: Pathname?
```
This PR fixes the problem.
=> Fix `FalseAssertion` diagnostic reporting

lib/steep/type_inference/type_env.rb, test/type_env_test.rb
In Ruby, even non-ascii characters can be used as local variables.
```
変数 = 1
```
However, when this code is checked with steep, it results in an `UnexpectedError`.
```
sample.rb:1:0: [error] UnexpectedError: 変数 is not a local variable
│ Diagnostic ID: Ruby::UnexpectedError
│
└ 変数 = 1
~~~~~~
```
This patch fixes it so that a variable with non-ascii characters does not result in an UnexpectedError.
=> Fix errors caused by non-ascii variable names

lib/steep/type_construction.rb, sample/lib/conference.rb, sig/steep/type_construction.rbs, test/type_construction_test.rb
Constant resolution in assignment has a special rule:
* It tries to look up a constant in current module nesting context
* No outer module nesting context lookup
* No ancestor constants lookup
=> Fix constant declaration type checking

lib/steep/type_construction.rb, sig/steep/type_construction.rbs, test/type_construction_test.rb
Implements the following assignment variants for global variables.
```ruby
$a, $b = array
$a ||= 123
$b += "hello"
```
Closes #695
=> Support gvasgn in assignment variants

lib/steep/diagnostic/lsp_formatter.rb, lib/steep/diagnostic/ruby.rb, test/type_construction_test.rb
=> Fix location no method error

lib/steep/subtyping/check.rb, sig/steep/subtyping/check.rbs, smoke/regression/Steepfile, smoke/regression/enumerator_product.rb
Closes #741
The loop was because of `Array[Integer] <: _EachEntry[A]` and `#each_entry` method type check.
=> Return immediately if blocks are incompatible

lib/steep/server/interaction_worker.rb
This helps generating better result in the following scenario.
```rbs
class Foo
attr_reader name: 👈 Start completion here
end
```
The RBS file has a syntax error and it starts completion with `nil` nesting context, while the user expects `::Foo`.
Setting `is_incomplete: true` in this case forces generating a new list after user typing some character, that would make the syntax correct.
=> Refresh completion list if RBS file has a syntax error

Gemfile.lock, steep.gemspec
Steep-1.4.0 contains signatures using "use" directive.  For that reason, steep can't work with rbs-2.x now.  So the dependency for RBS should be updated.
=> Update RBS to 3.0

lib/steep/server/lsp_formatter.rb, test/server/lsp_formatter_test.rb
Fixed a display error when a method name is sandwiched between `_` when hovering over a method.
=> Should escape underscore for method name

lib/steep/type_construction.rb, test/type_construction_test.rb
=> Add handling splat node in tuple type checking

lib/steep/type_construction.rb, sig/steep/type_construction.rbs, test/type_construction_test.rb
Closes #743.
It's possible to implement better type checking of splat nodes for the case it has tuple type, but it's not in this PR.
=> Handling splat nodes in `super`

lib/steep/diagnostic/ruby.rb
UnsupportedSyntax warnings are meaningless message for users.  So they should be suppressed by default.
refs: #787
=> Suppress UnsupportedSyntax warnings by default

lib/steep/diagnostic/ruby.rb, lib/steep/subtyping/variable_variance.rb, lib/steep/type_construction.rb, sig/steep/diagnostic/ruby.rbs, sig/steep/subtyping/variable_variance.rbs, test/type_construction_test.rb
Closes #666
1. It extracts the proc types from the hint for the case that is reported in #666
2. It confirms if only one proc type is included in the hint so that it can determine which proc type to use as its hint
3. Otherwise, it reports a diagnostic that the hint which is given to lambda is just ignored `ProcHintIgnored`
=> Better hint type handling given to lambda

.gitignore, .vscode/steep-shared.code-snippets, lib/steep/diagnostic/ruby.rb, lib/steep/drivers/check.rb, lib/steep/expectations.rb, lib/steep/type_construction.rb, lib/steep/type_inference/context.rb, sig/shims/language-server_protocol.rbs, sig/shims/parser/nodes.rbs, sig/steep/diagnostic/ruby.rbs, sig/steep/drivers/check.rbs, sig/steep/drivers/diagnostic_printer.rbs, sig/steep/expectations.rbs, sig/steep/type_construction.rbs, sig/steep/type_inference/context.rbs, test/expectations_test.rb, test/type_check_test.rb
Fixes #729 
This PR adds two new Ruby diagnostics -- `SetterBodyTypeMismatch` and `SetterReturnTypeMismatch`. The users can configure the diagnostics to make type checking consistent with RuboCop offense.
=> Add new diagnostic for setter methods

lib/steep.rb, lib/steep/ast/node/type_application.rb, lib/steep/ast/node/type_assertion.rb, lib/steep/node_helper.rb, lib/steep/server/interaction_worker.rb, lib/steep/server/lsp_formatter.rb, lib/steep/services/completion_provider.rb, lib/steep/source.rb, lib/steep/type_construction.rb, lib/steep/type_inference/context_array.rb, lib/steep/typing.rb, sig/shims/parser.rbs, sig/shims/parser/nodes.rbs, sig/steep/ast/node/type_application.rbs, sig/steep/ast/node/type_assertion.rbs, sig/steep/node_helper.rbs, sig/steep/services/completion_provider.rbs, sig/steep/source.rbs, sig/steep/type_inference/context_array.rbs, sig/steep/typing.rbs, test/ast/node/type_application_test.rb, test/completion_provider_test.rb, test/context_array_test.rb, test/lsp_formatter_test.rb, test/source_test.rb, test/type_construction_test.rb
Let RBS type name completion work in inline annotations, type assertions, and type applications.
```ruby
xs = []
path = nil #: Path  <= Here
```
Note that the completion in comments doesn't pop up automatically. You have to trigger completion explicitly, with `Ctrl+Space` or equivalent.
Closes #722
Closes #718
=> Completion in annotations

lib/steep/signature/validator.rb
Generating a shape for `class_var.location` takes seconds because it is a union type more than 10 constructs. `nil | RBS::Location[...] | RBS::Location[...] | RBS::Location[...] | ...`. Giving a type `RBS::Location[untyped, untyped]?` beforehand makes the shape generation much faster.
This change makes type checking the `validator.rb` using released (and the HEAD) version of Steep faster. Not an improvement of the type checking algorithm itself.
=> Cast from union for faster type checking

lib/steep/type_construction.rb, test/type_construction_test.rb
Do type narrowing if an early return statement uses "and return".
ex:
render and return unless user
refs: #824
=> Support early return code using "and return"

lib/steep/services/completion_provider.rb, sig/steep/services/completion_provider.rbs, test/completion_provider_test.rb
The optional chaining allows to developers to call method only if the receiver is not nil.  Therefore, CompletionProvider should consider the receiver is not nil if the optional chaining operator is given.
This fix unwraps the Optional[T] from receiver_type on completion for the optional chaining.  It will provide better completion for developers.
=> completion: Support completion for optional chaining (&.)

lib/steep/ast/types/factory.rb, lib/steep/type_construction.rb, lib/steep/type_inference/logic_type_interpreter.rb, sig/steep/ast/types/factory.rbs, smoke/and/a.rb, smoke/and/test_expectations.yml, test/type_check_test.rb, test/type_construction_test.rb
* Introduce `#unwrap_optional` and `#partition_union`, for safe-navigation-operator and truthy/falsy test
* Fix `UnreachableBranch` detection in `:if` typing
* Detect unreachable branch with `bot` type
* Refactor `:and` and `:or` node shortcut
=> Refactor occurrence typing

lib/steep/ast/node/type_application.rb, lib/steep/ast/node/type_assertion.rb, test/ast/node/type_application_test.rb, test/ast/node/type_assertion_test.rb, test/type_check_test.rb
It reports an type validation error like:
```
lib/steep/services/signature_help_provider.rb:65:16: [error] UnexpectedError: lib/steep/services/signature_help_provider.rb:65:28...65:32: ::Array expects parameters [Elem], but given args []
│ Diagnostic ID: Ruby::UnexpectedError
│
└         items = [] #: Array[Item]
~~~~~~~~~~~~~~~~~
```
=> Resolve type names from TypeAssertion and TypeApplication

lib/steep/type_construction.rb, sig/steep/type_construction.rbs, test/type_check_test.rb
Fixes #838 
The problem was because of `test_node = test.updated(:send, [test, :===, cond])`, where `cond` is reused and given multiple times to `synthesize` which results in updating the type of the `cond` node.
This PR introduces simplified transformation. The *condition* node is transformed using a fresh local variable `var_name`. And the type of `var_name` is propagated to the original `value_node` when it's type checking body of each `when`/`else` clauses.
=> Fix type-case

lib/steep/ast/types/factory.rb, test/type_check_test.rb, test/type_factory_test.rb
Let `Factory#partition_union` handle `top` types and nested union.
=> Fix `#partition_union`

lib/steep/type_construction.rb, lib/steep/type_inference/logic_type_interpreter.rb, test/type_check_test.rb, test/type_construction_test.rb
This PR fixes two case-when typing problems.
1. Case-when without subject may result in unexpected `UnreachableBranch`, when one `when` clause is detected *always* true and all of the following `when`s are *unreachable*.
2. Case-when with `untyped`, `top`, or `bool` subject with equality values results in `UnreachableBranch`.
This PR also reverts #841 because having no-`untyped` is better, while `bot` is the exception that `untyped` wins over `bot`.
=> Fix unreachability test

lib/steep/type_construction.rb, lib/steep/type_inference/context.rb, test/type_check_test.rb
Nested block calls with type variable reports unexpected type error.
```ruby
"".yield_self do       # { (String) -> X1 } -> X1
123.yield_self do    # { (Integer) -> X2 } -> X2
true               # bool
end
end
```
Here, we expect the type propagation from `bool` to `X2` to `X1`, but type checker first solves `X2` to `X1`. And `bool` cannot be `X1`, because `X1` is not a bound type variable in `123.yield_self` call.
This PR is to limit generating constraints between `X2` and `X1` only if the hint (`X1`) is a free variable of `self`. (For generic classes.)
This was caused by #789.
=> Fix type inference problem

lib/steep/server/interaction_worker.rb, lib/steep/services/completion_provider.rb, sig/steep/services/completion_provider.rbs, test/completion_provider_test.rb
=> Support completion for keyword arguments

lib/steep/server/interaction_worker.rb, lib/steep/services/signature_help_provider.rb, sig/steep/services/signature_help_provider.rbs, test/signature_help_provider_test.rb
=> Indicate the current or next argument on signature help

lib/steep/project/dsl.rb, sig/steep/diagnostic/ruby.rbs, sig/steep/project/dsl.rbs
Allow `#configure_code_diagnostics` receive both `template` and block to customize it.
=> Update `#configure_code_diagnostics` type

lib/steep/interface/builder.rb, sig/steep/interface/builder.rbs
Having `Self`, `Instance`, or `Class` as `self_type:`, `instance_type:`, or `class_type` may result in infinite recursive call of `#shape` which causes *interaction* worker unexpected exit with `SystemStackError`.
=> Avoid inifinite loop in `#shape`

lib/steep/type_inference/method_params.rb, test/method_params_test.rb
I encountered a pattern that was causing unexpected errors, so I have fixed it.
It seems that `<<` takes precedence over `||`.
This pattern was occurring with `Ripper.tokenize`.
https://github.com/ruby/ruby/blob/7816307b30189ec7d71d6ce704a9aebd0395d447/ext/ripper/lib/ripper/lexer.rb#L25
https://github.com/ruby/rbs/blob/abcc97d3c8b024856ba9603a7ef22d422652ff42/stdlib/ripper/0/ripper.rbs#L1097
```
$ cat t.rb
class Foo
def foo(**kw)
end
end
$ cat t.rbs
class Foo
def foo: (?a: boolish) -> void
end
$ cat Steepfile
target :app do
check "t.rb"
signature "t.rbs"
end
$ steep check
......................................................................[Steep 1.5.3] [typecheck:typecheck@2] [background] [#typecheck_source(path=t.rb)] [#type_check_file(t.rb@app)] [synthesize:(1:1)] [synthesize:(2:3)] …
```
=> Fix unexpected error when DifferentMethodParameterKind

lib/steep/subtyping/check.rb, test/subtyping_test.rb
It allows `nil` to be an `Object`.
=> `nil` is not a `NilClass`

lib/steep/cli.rb, sig/steep/cli.rbs, test/cli_test.rb
Steep invokes worker processes to type check files as many as the processors. But, computers running CI jobs typically have large number of processors, while the resources each CI job can use is limited.
Assume the CI computer has 32 cores, but only two of them are available for CI job. Steep spawns ~32 worker processes based on the number of cores. The problem is it often hits the memory limit by starting too many workers.
This PR is to fix the problem by setting the default `--jobs` number to `2` (or # of cores if it's smaller) when:
1. `CI` environment variable is defined, and
2. `--jobs` option is not set
This can slow the type checking job during CI if more than two cores are available. In that case, specify `--jobs` option explicitly based on the number of the available cores.
This …
=> Run with `--jobs=2` automatically on CI

lib/steep/server/interaction_worker.rb, lib/steep/services/completion_provider.rb, lib/steep/services/type_name_completion.rb, sig/steep/services/type_name_completion.rbs, test/type_name_completion_test.rb
Type name completion didn't work with module/class aliases or `use` directives
```rbs
use Foo as Foo2
module Foo
module Bar
end
end
module Foo1 = Foo
type t1 = Foo1::B    # <= Completion didn't work because `Foo1` is a module alias
type t2 = Foo2::B   # <= Completion didn't work because `Foo2` is a `use` type name
```
This also fixes a completion triggered with an _absolute_ type name -- `::Foo`.
=> Better completion with module alias and `use` directives

sig/shims/language-server_protocol.rbs
refs: https://github.com/mtsmfm/language_server-protocol-ruby/blob/main/lib/language_server/protocol/constant/message_type.rb
=> Add types for LSP::Constant::MessageType

lib/steep/cli.rb
I found some block arguments are wrongly named (maybe via copy-paste). It would be better to rename them all to "command".
=> refactor: Rename driver objects to command

lib/steep.rb, lib/steep/server/delay_queue.rb, lib/steep/server/master.rb, sig/steep/server/delay_queue.rbs, sig/steep/server/master.rbs, test/master_test.rb
Instead of waiting for a `didSave` notification, start type checking after `didChange` notification with 0.1secs delay.
This improves responsiveness especially with editor configuration without auto-save.
#933
=> Start type check on change

lib/steep/server/change_buffer.rb, lib/steep/server/master.rb, lib/steep/server/type_check_worker.rb, sig/steep/server/change_buffer.rbs
Let master forward `didOpen` notification to workers.
Workers reset the file content from the notification. This would provide a way to recover from broken buffer status.
Note that the `didOpen` notification won't start type checking. This may look weird, but won't cause an actual problem when we use the file watchers.
#933
=> Reset file content on `didOpen` notification

lib/steep/server/master.rb, lib/steep/server/type_check_worker.rb, sig/steep/server/master.rbs
Use LSP file watcher protocol for edits made by other tools.
The pattern syntax is [defined here](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#pattern). It looks like compatible with Ruby's glob syntax.
#933
=> Set up file watcher

lib/steep/type_construction.rb, sig/steep/diagnostic/ruby.rbs, smoke/block/test_expectations.yml, smoke/enumerator/test_expectations.yml, test/type_check_test.rb
`UnresolvedOverloading` error is not very helpful. The developers should read the error message carefully, and uncover what is causing type errors theirselves.
This PR is to report fewer `UnresolvedOverloading` by filtering arity type errors first.
If a required block is not given, we can guess it's not the intended method type overload. Same for other arguments.
Working for https://github.com/soutaro/steep/pull/937
=> Fewer `UnresolvedOverloading`

lib/steep/server/interaction_worker.rb
It was displaying the type of parameters of the method type, but it was confusing, when return types or block types are different.
This PR displays the whole method type in the popup.
=> Let label be whole method type in SignatureHelp

lib/steep/type_construction.rb, test/goto_service_test.rb
This fixes a bug that goto definition from method calls with errors don't work sometimes.
This is caused because `MethodCall::Error` instantiation doesn't have `method_decls` if `UnresolvedOverloading` is to be reported.
=> Let goto definition work from `UnresolvedOverloading` error calls

lib/steep/ast/types/logic.rb, lib/steep/interface/builder.rb, lib/steep/type_inference/logic_type_interpreter.rb, sig/steep/ast/types.rbs, sig/steep/ast/types/logic.rbs, test/logic_type_interpreter_test.rb, test/type_check_test.rb
Module#< and Module#<= means the argument is the ancestor of the receiver.  Thefore this allows to Steep to do narrowing the type of the receiver to the given argument.
=> Support type narrowing by `Module#<`

lib/steep/diagnostic/ruby.rb
Because of #941, new `BlockBodyTypeMismatch` may be reported. Having lower severity than `UnresolveOverloading` make the users feel the diagnostics are disappeared.
This is not what we want, and gibing higher severity will preserve the type errors.
=> Change severity of block diagnostics

lib/steep/services/completion_provider.rb, lib/steep/type_construction.rb, test/completion_provider_test.rb
It caused an error during completion:
```
[Steep 1.6.0.pre.1] [interaction:interaction] [background] Unexpected error: #<NoMethodError: undefined method `class?' for nil:NilClass>
[Steep 1.6.0.pre.1] [interaction:interaction] [background]   .../ruby/gems/3.2.0/gems/rbs-3.2.2/lib/rbs/environment.rb:337:in `normalize_module_name?'
[Steep 1.6.0.pre.1] [interaction:interaction] [background]   .../ruby/gems/3.2.0/gems/rbs-3.2.2/lib/rbs/environment.rb:333:in `normalize_module_name'
[Steep 1.6.0.pre.1] [interaction:interaction] [background]   .../ruby/gems/3.2.0/gems/rbs-3.2.2/lib/rbs/resolver/constant_resolver.rb:113:in `children'
[Steep 1.6.0.pre.1] [interaction:interaction] [background]   .../ruby/gems/3.2.0/gems/steep-1.6.0.pre.1/lib/steep/type_inference/constant_env.rb:38:in `children' …
```
=> Assign types on method calls in mlhs node

lib/steep/interface/builder.rb
`Object` methods are moved to `Kernel` in https://github.com/ruby/rbs/pull/1504. So Steep should test if the method is defined in `Kernel` in addition to `Object`.
=> Object methods are moved to Kernel

lib/steep/server/master.rb, sig/steep/server/master.rbs, test/master_type_check_controller_test.rb
`workspace/didChangeWatchedFiles` for opened files must be ignored because `textDocument/didChange` notification is also sent.
`TargetPaths` implementation had a bug that caused an issue that only the first target triggers type checking after edits.
=> Fix LSP text synchronization problems

lib/steep/services/file_loader.rb, test/file_loader_test.rb
During development of [this](https://github.com/dense-analysis/ale/pull/4671) I found out that this would work:
```
bundle exec steep check lib/foobar.rb
```
but this would fail:
```
bundle exec steep check /some/project/path/lib/foobar.rb
```
The pattern being relative, it had no chance to match the absolute path provided as argument.
Fixed by making absolute path relative to base_dir before checking against pattern.
=> Handle absolute path

lib/steep/drivers/utils/driver_helper.rb, lib/steep/drivers/worker.rb, lib/steep/project.rb, lib/steep/server/worker_process.rb, sig/steep/drivers/utils/driver_helper.rbs, sig/steep/project.rbs, sig/steep/server/worker_process.rbs, test/cli_test.rb
This allows Steep to work out-of-the-box with no further setup required.
Though of course users are encouraged to set up their `Steepfile` according to their project structure.
May relate to https://github.com/soutaro/steep-vscode/pull/227#issuecomment-1630886992
This matches the minimum (i.e., least set up) project structure of dumping everything in the project root.
* Utilize `nil`able `Steepfile` path in tests instead of leaving the `Steepfile` non-existent.
=> Default to check the entire current directory when there is no `Steepfile`

steep.gemspec
It is not necessary for runtime and makes it impossible to use the gem in symlink environments because of a space in "hello world.rb"
=> Ignore smoke tests when packaging gem

lib/steep.rb, lib/steep/cli.rb, lib/steep/drivers/utils/driver_helper.rb, lib/steep/drivers/worker.rb, lib/steep/project/dsl.rb, lib/steep/project/options.rb, lib/steep/server/worker_process.rb, sig/shims/yaml.rbs, sig/steep.rbs, sig/steep/drivers/utils/driver_helper.rbs, sig/steep/project/dsl.rbs, sig/steep/project/options.rbs, test/driver_helper_test.rb, test/steepfile_test.rb
This PR is to let Steep continue running even if rbs-collection is not correctly set up, while the type checking will fail.
Related to https://github.com/soutaro/steep/pull/969
It includes a commit about `Steep.ui_logger` which improves message printing.
=> Better recovery from collection problems

lib/steep/type_construction.rb, test/type_check_test.rb
Currently the "argument" given to `defined?` is typechecked—this doesn't exactly follow how Ruby handles `defined?`. (It evaluates everything up to the last method call).
A good usecase of this is to check if a method is defined (`raise "must have #foo method" unless defined? arg.foo`) as `.respond_to?` won't work on `top`s.
=> Make defined? accept any type

lib/steep/server/change_buffer.rb, lib/steep/server/interaction_worker.rb, lib/steep/type_construction.rb, sig/steep/server/change_buffer.rbs, sig/steep/server/interaction_worker.rbs, sig/steep/type_construction.rbs
It looks like completion requests are sent multiple times from VSCode and it waits for seconds to finish all of them, while only the last completion request makes sense.
This PR skips prior UI jobs before processing the last queued one.
* Pros: UI responsiveness improvements
* Cons: UI requests loss -- dropping completion request always makes sense, but how about SignatureHelp?
=> Skip pending UI jobs

lib/steep/server/interaction_worker.rb, lib/steep/services/signature_help_provider.rb, test/signature_help_provider_test.rb
Let signature help work inside block.
```rb
[1].each do |x|
x.abs()               # Has shown signature help for `Array#each` where `Integer#abs` is expected
end
```
=> Fix signature help

lib/steep/subtyping/check.rb, lib/steep/subtyping/result.rb, sig/steep/subtyping/check.rbs, sig/steep/subtyping/result.rbs, test/type_check_test.rb
Type checking `"" =~ ""` doesn't stop by infinitely recursive subtyping check.
```
interface _MatchAgainst[T]
def =~: (String) -> T
end
class String
def =~: (Regexp) -> Integer?
| [T] (_MatchAgainst[T]) -> T
end
"" =~ ""
String <: _MatchAgainst[T_1]                           # T_1 is a fresh type variable
=~
[T] (_MatchAgainst[T]) -> T <: (String) -> T_1     # Expand =~ method types
(_MatchAgainst[T_2]) -> T_2 <: (String) -> T_1   # Expand generics with fresh type variable T_2
String <: _MatchAgainst[T_2]                   # The first subtyping relationship but with T_2, and continues
T_2 <: T_1
```
Instead of causing `SystemStackError`, let subtyping check fail with new `LoopAbort` error.
=> Abort if subtyping fails to (possible) infinite loop

lib/steep/type_construction.rb, lib/steep/type_inference/block_params.rb, sig/steep/type_construction.rbs, sig/steep/type_inference/block_params.rbs, test/block_params_test.rb, test/type_construction_test.rb
I found two error patterns.
It seems to occur when the block argument is unnamed.
```ruby
m do |*|
1 if 1
#=> UnexpectedError: undefined method `start_with?' for nil(NoMethodError)
#=> 1. /Users/ksss/src/github.com/ksss/steep/lib/steep/type_inference/type_env.rb:316:in `local_variable_name?'
#=> 2. /Users/ksss/src/github.com/ksss/steep/lib/steep/type_inference/type_env.rb:323:in `local_variable_name!'
#=> 3. /Users/ksss/src/github.com/ksss/steep/lib/steep/type_inference/type_env.rb:115:in `block in assign_local_variables'
end
```
```ruby
m do |(*)|
1 if 1
#=> UnexpectedError: undefined method `start_with?' for nil(NoMethodError)
#=> 1. /Users/ksss/src/github.com/ksss/steep/lib/steep/type_inference/type_env.rb:316:in `local_variable_name?'
#=> 2. …
```
=> Fix UnexpectedError with unnamed arguments 

lib/steep/type_construction.rb, test/type_check_test.rb
Closes #1079 
Confirmed there is no problem with `&&` type narrowing.
=> Fix  method call type narrowing with`||` operator

lib/steep/signature/validator.rb
This PR reduces `RBS::Location#to_s` calls.
Currently, this method is called for debug logging but it is unnecessary unless the log level is debug. So I replaced the string literal with a block. 
This change is necessary because I want to make `RBS::Location` slim. I plan to remove `line` and `column` information in this change to reduce memory usage.
This debug logging is the only call of the method during `steep check`. Therefore we can make it slim safely if this method call is removed.
I've confirmed the `RBS::Location#to_s` calls with the following patch for RBS.
```diff
diff --git a/lib/rbs/location_aux.rb b/lib/rbs/location_aux.rb
index 769f91c5..53203d3f 100644
--- a/lib/rbs/location_aux.rb
+++ b/lib/rbs/location_aux.rb
@@ -45,13 +45,13 @@ module RBS
def start_loc
@start_loc ||= …
```
=> Avoid unnecessary calling `RBS::Location#to_s` on debug log

lib/steep/services/file_loader.rb, test/file_loader_test.rb
Fixed soutaro/steep#1109
Adjusted processing to apply `Pathname.glob` for wildcard expansion before subsequent processing. 
As a result, eliminated cases where `absolute_path` is neither a file nor a directory, and removed the unnecessary branching logic.
=> Fix issue with wildcard expansion in FileLoader

lib/steep/server/interaction_worker.rb, test/interaction_worker_test.rb
The custom LSP request is handled in TypeCheckWorker, but the implementation in InteractionWorker slipped my mind in #936.
The result was confusing while I was testing RBS::Inline gem. The diagnostics was reported because it's done be TypeCheckWorker, but the completion or hover doesn't work. Checking the updated RBS file resumes the interaction worker, because opening the file means the `textDocument/didChange` notifications are sent to language server.
=> Handle `$/file/reset` request in interaction worker

lib/steep/project/pattern.rb, test/pattern_test.rb
Fixed soutaro/steep#1120
Prior to this commit, the `Pattern` class used `String#start_with?` for pattern matching when directory names were specified in the patterns array. 
This method did not support the expansion of wildcards, which led to files that should have been matched by wildcard patterns being omitted from the `steep stats` output. 
By replacing `String#start_with?` with `File.fnmatch`, this commit ensures that wildcards are correctly expanded even when matching directory patterns, thereby resolving the mismatch issue.
The tests added to `pattern_test.rb` confirm that the new pattern matching logic correctly identifies files within directories that match wildcard patterns, ensuring robustness of this fix and preventing future regressions.
=> Improve wildcard handling in pattern matching for directory paths

lib/steep/type_construction.rb, test/ruby_hover_test.rb
When writing `rescue StandardError => e`, `e` should be an instance of the `StandardError` class. 
However, variables declared in rescue clauses would become untyped on hover in some cases.
```ruby
class Hello
def do_something(x)
x
rescue StandardError => e
e.message # `e` becomes untyped on hover
e # `e` is StandardError on hover
end
end
```
This issue is fixed by explicitly updating the context.
=> Fix variable untyped hover issue in rescue clause

steep.gemspec
Retry: https://github.com/soutaro/steep/pull/1074
Fix: https://github.com/soutaro/steep/issues/1072
Some signatures in Steep's sig directory conflict with those in gem_rbs_collection, making them difficult to use.
Additionally, code that uses Steep's class/module/interface does not seem to have many use cases.
To resolve this issue, I propose excluding the `sig` directory from the steep gem package.
=> Stop to distribute sig dir

lib/steep/rake_task.rb, sig/steep/rake_task.rbs, test/rake_task_test.rb
1. Focus on more frequently used (based on my guess) subcommands
2. Type check the implementation
3. Add `<<` method to specify options of commands
=> Revise rake tasks

doc/shape.md, lib/steep/interface/builder.rb, lib/steep/signature/validator.rb, lib/steep/subtyping/check.rb, rbs_collection.steep.yaml, sig/steep/interface/builder.rbs, sig/steep/signature/validator.rbs, test/validation_test.rb
Steep 1.7.0 introduces a new constraint that `self` cannot include `instance` and `class` types, and vice versa. This causes an unexpected type checking failure on FFI as reported in https://github.com/soutaro/steep/issues/1162.
This PR fixes the problem by delaying the constraint checking until the shape of `self` type is needed.
https://github.com/soutaro/steep/issues/916 is also fixed by handling the `self`, `instance`, and `class` types during validation.
Fixes https://github.com/soutaro/steep/issues/1162, https://github.com/soutaro/steep/issues/916.
=> Fix subtyping issues

lib/steep/source.rb, test/source_test.rb
This improves the compatibility with `rbs-inline`, where `attr_*` calls may be annotated for the type of the attributes.
Steep now ignores `#:` annotations given to `attr_reader`, `attr_accessor`, and `attr_writer` calls without receivers. If you really need some type annotation to your custom `attr_reader` (likes) calls, you need to add `self.` receiver or surround them with parens.
```rb
class Foo
attr_reader :foo #: String
self.attr_reader :foo #: String
(attr_reader :foo) #: String
end
```
=> Ignore `#:` annotation on `attr_*` calls

lib/steep/type_construction.rb, test/type_construction_test.rb
Currently, steep does not support the syntax for `1r`, `1i`  and `1ri`, and they default to `untyped` type.
In this PR, I have made it possible to interpret `1r` as `Rational`, `1i` as `Complex` and `1ri` as `Complex`.
=> Support literals for Rational and Complex

lib/steep/server/master.rb
Probably this PR fixes https://github.com/soutaro/steep/issues/661.
The execution time of `steep check` increases with `O(n^2)` order (n == number of files).
This PR improves the performance. The order will probably be `O(n)`.
`TypeCheckRequest#all_paths` is called on each file. This method allocates a large `Set` if `steep check` checks many files. It makes `steep check` slow.
Avoid allocating the large set in `all_paths` method.
I benchmarked `steep check` command with the following script, creating many `.rb` and `.rbs` files.
```ruby
require 'pathname'
lib = Pathname('lib').tap { _1.rmtree; _1.mkpath }
sig = Pathname('sig').tap { _1.rmtree; _1.mkpath }
ARGV.first.to_i.times do |i|
lib.join("foo#{i}.rb").write(<<~RUBY)
class Foo#{i}
end
RUBY
sig.join("foo#{i}.rbs").write(<<~RUBY)
class …
```
=> Improve performance when there are many files

README.md
I've added basic linter-mode support for `steep` in ALE for Vim/Neovim in https://github.com/dense-analysis/ale/pull/4671 so let's document that and hopefully get a bit more `steep` adoption!
Hopefully someday I'll find a way to add proper LSP mode (which kind of works but had some brokenness last time I checked)
=> Add Vim linting information

guides/src/gem-rbs-collection/gem-rbs-collection.md
Fix a typo (missing single quote) in the `guides/src/gem-rbs-collection/gem-rbs-collection.md`
=> Fix typo (gem-rbs-collection.md)

lib/steep/services/completion_provider.rb, test/completion_provider_test.rb
The error is caused by calculating the type of method call, where the receiver is `self`. Resolving the `self`-ish types beforehand fixes the problem.
=> Fix shape calculation error

lib/steep.rb, lib/steep/server/change_buffer.rb, lib/steep/server/interaction_worker.rb, lib/steep/server/master.rb, lib/steep/server/type_check_worker.rb, rbs_collection.steep.yaml, sig/steep/server/change_buffer.rbs, sig/steep/server/master.rbs, sig/steep/server/type_check_worker.rbs, test/interaction_worker_test.rb, test/master_type_check_controller_test.rb, test/type_check_worker_test.rb
Loading Ruby scripts and app signature files in each worker processes causes busy disk IO. Loading all of the files in main process and send them with custom LSP events would improve the busy disk IO and make it faster.
=> Load files in main process

lib/steep.rb, lib/steep/drivers/check.rb, lib/steep/drivers/checkfile.rb, lib/steep/drivers/stats.rb, lib/steep/drivers/utils/driver_helper.rb, lib/steep/drivers/watch.rb, lib/steep/server/master.rb, lib/steep/server/type_check_worker.rb, lib/steep/server/work_done_progress.rb, sig/steep/drivers/utils/driver_helper.rbs, sig/steep/server/master.rbs, sig/steep/server/work_done_progress.rbs, test/lsp_double.rb, test/master_test.rb, test/master_type_check_controller_test.rb, test/master_type_check_request_test.rb
Loading bigger project takes seconds, and the language server blocks while scanning all of the files. This PR shows a progress message with `loading project` to let the users know what is happening.
=> Print `loading project` message via LSP

lib/steep/server/master.rb
Test fails with `ThreadError` on `#push` with ruby-3.0 and ruby-3.1.
```
/home/runner/work/steep/steep/lib/steep/server/master.rb:1028:in `push': queue full (ThreadError)
```
This is because the `timeout:` keyword arg is introduced at Ruby 3.2, so the `push(object, timeout: nil)` is equivalent to `push(object, true)` which means raising error immediately when queue is full.
Deleting `timeout: nil` would solve the problem.
=> No `timeout: nil`

Gemfile, Gemfile.lock, lib/steep.rb, lib/steep/ast/types/factory.rb, lib/steep/interface/builder.rb, lib/steep/interface/type_param.rb, lib/steep/server/lsp_formatter.rb, lib/steep/signature/validator.rb, lib/steep/subtyping/check.rb, lib/steep/type_construction.rb, lib/steep/type_inference/logic_type_interpreter.rb, sig/steep/ast/types/factory.rbs, sig/steep/interface/type_param.rbs, smoke/and/a.rb, smoke/diagnostics/else_on_exhaustive_case.rb, smoke/diagnostics/unsupported_syntax.rb, steep.gemspec, test/subtyping_test.rb, test/type_check_test.rb, test/type_construction_test.rb
See https://github.com/ruby/rbs/pull/1994 for rbs updates.
=> Improve generics

lib/steep/interface/builder.rb, lib/steep/interface/type_param.rb, lib/steep/subtyping/check.rb, lib/steep/type_construction.rb, sig/steep/interface/type_param.rbs, test/type_check_test.rb
Found that the implicit upper bound causes issues with `void` and interface types. 😢
=> Revert implicit generic upper bound

lib/steep/ast/types/factory.rb, lib/steep/ast/types/record.rb, lib/steep/interface/builder.rb, lib/steep/subtyping/check.rb, lib/steep/subtyping/constraints.rb, lib/steep/type_construction.rb, lib/steep/type_inference/send_args.rb, sig/steep/ast/types/record.rbs, smoke/hash/test_expectations.yml, test/type_check_test.rb
The semantics of optional keys in record in Steep is *the hash may not have any value associated with the optional key*.
So, 
1. Assigning a hash without the optional key is allowed -- `{ id: 123 } #: { id: Integer, ?name: String }`
2. Having incompatible type with the optional key is prohibited (but, it causes unsoundness...)
3. The `#[]` operator of the record type returns an optional type, `#fetch` returns non-optional type (if the value type is not an optional)
=> Support optional keys in record types

lib/steep/ast/builtin.rb, lib/steep/interface/builder.rb, lib/steep/type_construction.rb, sig/steep/ast/builtin.rbs, sig/steep/interface/builder.rbs, sig/steep/type_construction.rbs, test/type_check_test.rb
It cannot be written with `class` and other ways in RBS.
Related to https://github.com/ruby/rbs/pull/2020
=> Add special path for `Kernel#class` method

steep.gemspec
Dependabot is failing because `vernier` gem requires Ruby `>= 3.2.0`, but dependabot is using Ruby 3.1. 
They detect the Ruby version they use from the .gemspec. So, adding a dummy `required_ruby_version` call would tell dependabot to use Ruby 3.3.
https://github.com/dependabot/dependabot-core/blob/main/bundler/lib/dependabot/bundler/file_updater/ruby_requirement_setter.rb
=> Add dummy `required_ruby_version`

lib/steep/interface/builder.rb, test/interface_builder_test.rb
Add a default overloading with the *backtype* of the keys, instead of the union of the key types.
```rb
hash = { id: 123, name: "foo" } #: { id: Integer, name: String }
hash[:id]              # => Integer
hash[:name]            # => String
hash["id".to_sym]      # => Integer | String, not a type error
```
This is more consistent with tuple types.
=> Fix record shape

lib/steep/type_construction.rb, sig/steep/type_construction.rbs, test/type_check_test.rb
Having a hint of union type with `Hash[untyped, untyped]` caused unexpected `FallbackAny` diagnostics.
```rbs
Account.joins(group: :category)    # => The argument has `FallbackAny` diagnostic
```
This PR fixes the problem.
=> Fix untyped hash typing

lib/steep/server/master.rb, sig/shims/language-server_protocol.rbs
The `DELETED` notification is `3`, not `4`, and caused unexpected `nil` content sent to workers.
Closes #1236 #1237
=> Handle file deletion notification

lib/steep/drivers/utils/driver_helper.rb, sig/steep/drivers/utils/driver_helper.rbs, test/driver_helper_test.rb
#1344 
It runs `rbs collection --frozen` (equivalent) if
* Collection lock file is generated, and
* RBS files are missing
=> Install rbs collection automatically

lib/steep/cli.rb, lib/steep/drivers/check.rb, sig/steep/drivers/check.rbs
`target` for `--validate` option doesn't make sense because the library configuration is shared among groups in a target. So, specifying every groups in a target validates correctly.
=> Delete `target` from `--validate` option

lib/steep/expectations.rb, lib/steep/interface/shape.rb, lib/steep/server/change_buffer.rb, lib/steep/server/interaction_worker.rb, lib/steep/server/type_check_worker.rb, lib/steep/services/completion_provider.rb, lib/steep/services/goto_service.rb, lib/steep/services/hover_provider/rbs.rb, lib/steep/services/hover_provider/ruby.rb, lib/steep/services/type_check_service.rb, lib/steep/signature/validator.rb, lib/steep/source.rb, lib/steep/subtyping/check.rb, lib/steep/subtyping/constraints.rb, lib/steep/type_construction.rb, lib/steep/type_inference/context.rb, lib/steep/type_inference/method_params.rb, lib/steep/type_inference/type_env.rb
135 -> 47
Note: `Hash#fetch` raises KeyError. So we need to merge this carefully. I'm okay to divide this PR to smaller ones.
=> refactor: Use Hash#fetch instead of Hash#[] to resolve type errors

lib/steep/ast/builtin.rb, lib/steep/interface/function.rb, lib/steep/interface/method_type.rb, lib/steep/type_construction.rb, sig/steep/ast/builtin.rbs, sig/steep/interface/function.rbs, sig/steep/interface/method_type.rbs, test/type_construction_test.rb
Pass `&method(:name)` to the block argument on method call is usually used, and well-known idiom in Ruby.  Therefore it is valuable to support the idiom on type check.
This gives a special treatment to it to support type checking.
=> Support &method(:name) call for block_pass

lib/steep/drivers/init.rb
As far as I know, Steep does not support type checking Gemfile. Therefore it's not good to use `Gemfile` as an example for specifying specific file.
This replaces it with actual .rb file case.
As a trial, I uncommented the line and tried to check `Gemfile`. But I got the following errors:
```
tkomiya@tarf> bundle exec steep check                                                                                                                                      ~/work/tmp/tmptmp
...................................................................F................
Gemfile:3:0: [error] Type `::Object` does not have method `source`
│ Diagnostic ID: Ruby::NoMethod
│
└ source "https://rubygems.org"
~~~~~~
Gemfile:5:0: [error] Type `::Object` does not have method `gem`
│ Diagnostic ID: …
```
=> Update filename example in initial Steepfile

manual/annotations.md
These syntax were added in Steep-1.3.
refs: https://github.com/soutaro/steep/wiki/Release-Note-1.3#add-type-assertion-and-type-application-syntax
=> docs: Add document for type assertion and type application

.github/workflows/ruby.yml, .vscode/steep-shared.code-snippets, Steepfile, bin/generate-diagnostics-docs.rb, guides/README.md, guides/src/diagnostics/ruby.md, sig/steep/diagnostic/ruby.rbs
When running steep check, various errors are displayed, but there is no clear explanation of what these errors mean.
So I created a document for error reference.
Japanese version: https://tech.timee.co.jp/entry/2024/10/02/153330
=> doc: Add diagnostics for Ruby page

README.md
XOR is not a good hash function, and this example might give people the wrong idea.
Better to just outsource to the built-in Hash function used by `Array`. It's more idiomatic, and will lead to less collisions.
=> Update example to not use `^` as a hash function

lib/steep/server/master.rb, sig/steep/server/master.rbs
Because we assume each file belongs to a target, we don't have to accumulate the diagnostics, but just forwarding to the client works.
=> Stop accumulating diagnostics

lib/steep/ast/types/factory.rb, test/logic_type_interpreter_test.rb, test/type_check_test.rb, test/type_factory_test.rb
It would be better to emit UnreachableBranch diagnostics to use "void" variables for if-conditions.
=> emit UnreachableBranch to the "void" condition

lib/steep/cli.rb, lib/steep/drivers/check.rb, lib/steep/server/type_check_controller.rb, sig/steep/drivers/check.rbs, test/cli_test.rb
The semantics of `target` is changed in `steep check` command, which is aligned to `Type check groups` command in LSP.
- The `target` syntax means files that belongs to the target directly, not to the groups in the target
- The `target.* syntax means all files under the target
=> Introduces a new `target.*` syntax for everything in the target

Gemfile.lock, steep.gemspec
`URI.encode_uri_component` was added since uri-v0.12.  Therefore we need to add it to the dependencies list to use the method.
Closes: #1399
=> deps: Add uri gem to dependencies list

lib/steep/source.rb, rbs_collection.steep.lock.yaml, test/source_test.rb
Type assertion should be attached to the value of keyword arg `pair`, not the `pair` node itself.
This allows writing type assertion for keyword args:
```rb
foo(
array: [] #: Array[String]
)
```
This issue is reported from @Little-Rubyist. Thanks! 🙏
=> Attach type assertion to keyword args

lib/steep/subtyping/check.rb, sig/test/subtyping_test.rbs, sig/test/type_check_test.rbs, smoke/hash/d.rb, smoke/hash/test_expectations.yml, test/subtyping_test.rb, test/type_check_test.rb
* The length of the tuple types *must be* same
* Record type with additional key *cannot* be a subtype of another record type
=> Strict record and tuple subtyping

lib/steep/type_inference/logic_type_interpreter.rb, sig/steep/type_inference/logic_type_interpreter.rbs, sig/test/type_check_test.rbs, test/type_check_test.rb
This tries to narrow types unions by the return type of the method call. If the return type of the method is always truthy or falsy, the receiver type will be narrowed on the truthy branch and the falsy branch.
This helps to narrow types via method definitions (ex. `#nil?`, `#present?`, `#blank?` and so on).
=> Type narrowing union types via return type of method call

lib/steep/subtyping/check.rb, test/type_check_test.rb
This fixes the case where a method can return either `self` or another value (e.g. `-> (self | nil)`).
Here's the concrete example: https://github.com/DataDog/dd-trace-rb/blob/5361e8e9a7092ca081ff0d5126daf8950bb2c792/lib/datadog/tracing/span_operation.rb#L202-L223
```ruby
def stop(stop_time = nil)
return if stopped?
now = Core::Utils::Time.now.utc
start(stop_time || now) unless started?
@end_time = stop_time || now
@duration_end = stop_time.nil? ? duration_marker : nil
events.after_stop.publish(self)
self
end
```
Currently this fails with:
```
Cannot allow method body have type `self` because declared as type `(self | nil)`
Diagnostic ID: Ruby::MethodBodyTypeMismatch
```
=> Fix self union type checking

lib/steep/services/signature_service.rb, smoke/diagnostics-rbs/invalid-type-application-class.rbs, smoke/diagnostics-rbs/invalid-type-application-module.rbs, smoke/diagnostics-rbs/test_expectations.yml
ref: https://github.com/ruby/rbs/pull/2289
When `InvalidTypeApplicationError` occurs in the RBS validator, there is a possibility that Steep will raise an **Unexpected error** if the type argument is `RBS::Types::ClassInstance`, `RBS::Types::Interface`, or `RBS::Types::Alias`.
This PR fixes the issue so that problems are reported correctly.
=> Support `InvalidTypeApplication` on `#update_env`

lib/steep.rb, lib/steep/cli.rb, lib/steep/drivers/check.rb, lib/steep/drivers/diagnostic_printer.rb, lib/steep/drivers/diagnostic_printer/base_formatter.rb, lib/steep/drivers/diagnostic_printer/code_formatter.rb, lib/steep/drivers/diagnostic_printer/github_actions_formatter.rb, test/cli_test.rb, test/diagnostics_printer_test.rb
I will add a formatter for GitHub Actions.  
By using this formatter in GitHub Actions, it will become easier to display type errors directly in code reviews on github.com.
The default behavior remains unchanged.
Rubocop has a similar feature, and it is also used in [the rbs repository](https://github.com/ruby/rbs/blob/1209f49fd9073374d5660e8d9fc25ce2fc5c1af0/Rakefile#L150).
You can see the demo by https://github.com/ksss/rubocop-on-rbs/pull/86/files also.
=> Implement GitHub formatter

lib/steep/type_inference/logic_type_interpreter.rb, sig/steep/type_inference/logic_type_interpreter.rbs, test/type_check_test.rb
This PR fixes type checking the following Ruby code:
```
if location = node.location         # Assume `node` has a union type
end
```
=> Fix union self type refinement based on method call

lib/steep/annotations_helper.rb, lib/steep/diagnostic/lsp_formatter.rb, lib/steep/diagnostic/signature.rb, lib/steep/server/interaction_worker.rb, lib/steep/services/completion_provider.rb, lib/steep/signature/validator.rb, sample/lib/deprecated.rb, sample/sig/deprecated.rbs, sig/steep/annotations_helper.rbs, sig/steep/diagnostic/signature.rbs, sig/steep/signature/validator.rbs, test/validation_test.rb
Note that it doesn't print diagnostics correctly -- without strikethrough -- for deprecated type names embedded in Ruby code.
=> Add deprecation validation on RBS

lib/steep/services/signature_service.rb
In ancestors error checking, the same issue may be reported multiple times.  
```
$ cat sample.rbs
class InheritModule < Kernel
end
$ bundle exec steep check
F
sample.rbs:1:22: [error] Cannot inherit from a module `::Kernel`
│ Diagnostic ID: RBS::InheritModuleError
│
└ class InheritModule < Kernel
~~~~~~
sample.rbs:1:22: [error] Cannot inherit from a module `::Kernel`
│ Diagnostic ID: RBS::InheritModuleError
│
└ class InheritModule < Kernel
~~~~~~
Detected 2 problems from 1 file
```
This happens because both `#one_instance_ancestors` and `#one_singleton_ancestors` in `RBS::DefinitionBuilder::AncestorBuilder` generate the same error.  
This issue can be reproduced by running the following command in the `smoke/diagnostics-rbs` directory:  
```sh
$ bundle exec steep check …
```
=> Dedup error message on ancestors check

lib/steep/type_construction.rb, test/type_check_test.rb
Closes https://github.com/soutaro/steep/issues/1522
The issue is caused by type checking the `receiver` twice (per call) by `synthesize_children`. Having `skips:` keyword with `receiver` solves the problem.
=> Fix type checking block calls on `untyped` receiver

lib/steep/type_construction.rb, sig/test/type_check_test.rbs, test/type_check_test.rb
The following example unexpectedly type checks.
```rb
Foo.foo() { 1 }.foooooo       # NoMethod error is expected, but the inferred return type is untyped
```
This is because `T` is resolved to `untyped` after type checking parameters -- no constraint is given because the positional argument is omitted here.
This PR delays the resolution if the block return type/return type is `T`.
=> Delay type variable resolution on method call with blocks

lib/steep/server/type_check_worker.rb, sig/steep/server/type_check_worker.rbs
Call `Process.warmup` before reforking to improve memory usage.
`Process.warmup` does major GC, memory compaction, and returns unused memory to the OS.
It's designed to be called before `fork` to reduce memory usage.
I benchmarked the memory usage with `free` command on a Rails app.
https://docs.google.com/spreadsheets/d/1dMhuYqEdbxcuxE-a-fy_X5g6-5_Dn3IHfLO_xPQj1Pg/edit?usp=sharing
The summary is:
* When `warmup` is called, it reduces ~1.7GB (33%) memory compared to the current implementation.
* When `warmup` is called, it reduces ~4.1GB (55%) memory compared to that if Steep does not refork.
=> Call `Process.warmup` before refork

Gemfile.lock, sample/Steepfile, sample/lib/inline.rb, sig/test/signature_controller_test.rbs, test/signature_controller_test.rb
That issue was essentially fixed in RBS (https://github.com/ruby/rbs/pull/2551).
=> Fix empty comment error

lib/steep/locator.rb, sig/steep/locator.rbs, test/locator_test.rb
Avoid having `SuperClass` AST directly in the result.
=> Fix `Locator::Inline`
